"use client"

import { createContext, useContext } from "react"

// Define supported languages
export type Language = "en" | "zh" | "ms" | "ta" | "ar"

// Define the context type
type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string>) => string
  getDirection: () => "ltr" | "rtl"
  isRTL: boolean
  languageName: (code: Language) => string
}

// Create the context with default values
export const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  getDirection: () => "ltr",
  isRTL: false,
  languageName: () => "",
})

// Custom hook for using the language context
export function useTranslation() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider")
  }
  return context
}

// Translation data for all supported languages
const translations = {
  en: {
    // Common
    "common.language": "Language",
    "common.english": "English",
    "common.chinese": "中文",
    "common.malay": "Bahasa Melayu",
    "common.tamil": "தமிழ்",
    "common.arabic": "العربية",
    "common.learnMore": "Learn More",
    "common.contactMe": "Contact Me",
    "common.downloadResume": "Download Resume",
    "common.resume": "Resume",
    "common.scrollTo": "Scroll to {section}",
    "common.loading": "Loading...",
    "common.close": "Close",
    "common.open": "Open",
    "common.view": "View",
    "common.hide": "Hide",
    "common.show": "Show",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.all": "All",
    "common.none": "None",
    "common.yes": "Yes",
    "common.no": "No",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Info",

    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.experience": "Experience",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.services": "Services",
    "nav.testimonials": "Testimonials",
    "nav.education": "Education",
    "nav.contact": "Contact",
    "nav.scrollTo": "Scroll to {section}",

    // Hero
    "hero.tagline": "Crafting Digital Solutions",
    "hero.title": "Kaung Sithu Linn",
    "hero.subtitle": "Software Developer",
    "hero.jobTitle": "Software Developer",
    "hero.description": "Results-driven developer with 4+ years of experience crafting intuitive user interfaces, conducting thorough testing, and delivering high-quality applications that meet complex requirements. Specializing in POS systems, fraud detection, and behavioral biometrics.",
    "hero.githubProfile": "GitHub Profile",
    "hero.linkedinProfile": "LinkedIn Profile",
    "hero.emailContact": "Email Contact",
    "hero.portfolioWebsite": "Portfolio Website",
    "hero.downloadResume": "Download Resume",
    "hero.resume": "Resume",
    "hero.learnMore": "Learn More",
    "hero.contactMe": "Contact Me",
    "hero.profileImageAlt": "Kaung Sithu Linn - Software Developer",

    // About
    "about.title": "About Me",
    "about.paragraph1": "As a passionate Software Developer based in Singapore, I specialize in developing robust applications with a focus on user experience and system optimization. With over 4 years at eVolva Software House, I've transformed business operations through innovative POS systems and network solutions.",
    "about.paragraph2": "My recent research focuses on cutting-edge behavioral biometrics and fraud detection using machine learning. I'm also certified in digital marketing fundamentals, allowing me to bridge technical development with effective market strategies. I'm currently pursuing my Master's in Information Technology with a Business Informatics major at James Cook University Singapore, where I continue to expand my expertise in data analytics and AI applications.",
    "about.quote": "I believe in creating technology that not only solves problems but enhances human experiences. My goal is to build secure, efficient, and user-friendly solutions that make a real difference.",
    "about.decorativeImageAlt": "Decorative background",
    "about.skills.frontend.title": "Frontend",
    "about.skills.frontend.description": "JavaScript, HTML5, CSS, UI Design",
    "about.skills.backend.title": "Backend",
    "about.skills.backend.description": "Python, Java, C++, .NET",
    "about.skills.database.title": "Database",
    "about.skills.database.description": "SQL, Data Management",
    "about.skills.ai.title": "AI/ML",
    "about.skills.ai.description": "Behavioral Biometrics, Deep Learning",
    "about.skills.marketing.title": "Digital Marketing",
    "about.skills.marketing.description": "SEO, Analytics, Content Strategy",
    "about.skills.languages.title": "Languages",
    "about.skills.languages.description": "English, Burmese, Chinese, Japanese",
    
    // Header
    "header.about": "About",
    "header.experience": "Experience",
    "header.skills": "Skills",
    "header.services": "Services",
    "header.education": "Education",
    "header.contact": "Contact",
    
    // Skills
    "skills.title": "Skills & Expertise",
    "skills.frontend": "Frontend Development",
    "skills.frontend.tech": "JavaScript, HTML5, CSS",
    "skills.frontend.desc": "Building responsive and interactive user interfaces with modern web technologies.",
    "skills.backend": "Backend Development",
    "skills.backend.tech": "Python, Java, C++, .NET",
    "skills.backend.desc": "Creating robust server-side applications with focus on performance and reliability.",
    "skills.database": "Database Management",
    "skills.database.tech": "SQL, Data Management",
    "skills.database.desc": "Designing and implementing efficient database schemas and queries for optimal data management.",
    "skills.uiux": "UI/UX Design",
    "skills.uiux.tech": "User Interface Design",
    "skills.uiux.desc": "Crafting intuitive user interfaces with focus on usability and accessibility.",
    "skills.ml": "Machine Learning",
    "skills.ml.tech": "Behavioral Biometrics, Deep Learning",
    "skills.ml.desc": "Developing ML models for fraud detection and user authentication using behavioral patterns.",
    "skills.programming": "Programming Languages",
    "skills.programming.tech": "JavaScript, Python, Java, C++",
    "skills.programming.desc": "Writing efficient code across multiple programming languages for diverse applications.",
    "skills.multilingual": "Multilingual",
    "skills.multilingual.tech": "English, Burmese, Chinese, Japanese",
    "skills.multilingual.desc": "Communicating effectively across multiple languages for international collaboration.",
    "skills.communication": "Communication",
    "skills.communication.tech": "Technical Writing, Public Speaking",
    "skills.communication.desc": "Conveying complex technical concepts clearly to both technical and non-technical audiences.",
    "skills.optimization": "System Optimization",
    "skills.optimization.tech": "Performance Tuning, Network Solutions",
    "skills.optimization.desc": "Enhancing system performance and resolving complex technical issues for optimal operation.",
    "skills.research": "Research",
    "skills.research.tech": "Academic Research, Literature Review",
    "skills.research.desc": "Conducting thorough research to identify gaps and propose innovative solutions in technology.",

    // Experience
    "experience.title": "Professional Experience",
    "experience.company": "eVolva Software House",
    "experience.location": "Mandalay, Myanmar",
    "experience.period": "Dec 2018 - Present",
    "experience.role": "Software Developer and Client Tester",
    "experience.responsibilities.1": "Designed and developed a POS system using Microsoft .NET to streamline stock and inventory management, improving operational efficiency",
    "experience.responsibilities.2": "Upgraded an outdated Microsoft Access (Office 2003) POS system to a modern SQL standalone application, enhancing performance",
    "experience.responsibilities.3": "Resolved LAN interference issues with the VPN network by implementing a custom tunneling solution, ensuring stable connectivity",
    "experience.responsibilities.4": "Delivered an optimized POS system that increased store efficiency by over 50%, reducing transaction time and improving inventory tracking",
    "experience.responsibilities.5": "Conducted comprehensive testing and client training to ensure seamless adoption of new systems",
    "experience.decorativeImageAlt": "Decorative background",
    "experience.keyAchievements": "Key Achievements",
    
    // Projects
    "projects.title": "Featured Projects",
    "projects.viewProject": "View Project",
    "projects.hideCase": "Hide Case Study",
    "projects.viewCase": "View Case Study",
    "projects.challenge": "Challenge",
    "projects.approach": "Approach",
    "projects.results": "Results",
    "projects.technologies": "Technologies Used",
    "projects.project1.title": "Mouse Dynamics for Online Assessment Fraud Detection",
    "projects.project1.period": "May 2024 - Nov 2024",
    "projects.project1.description": "Developed a machine learning model to detect fraudulent behavior during online assessments using mouse dynamics as a behavioral biometric.",
    "projects.project1.achievement1": "Analyzed mouse movement and click patterns to create user profiles and identify anomalies indicative of fraud",
    "projects.project1.achievement2": "Implemented feature selection techniques and evaluated multiple machine learning models, achieving high accuracy in fraud detection",
    "projects.project1.achievement3": "Identified key mouse dynamics features that are most discriminative for user authentication",
    "projects.project1.challenge": "Educational institutions faced increasing incidents of cheating in online assessments, with traditional proctoring methods proving insufficient for detecting sophisticated fraud techniques.",
    "projects.project1.approach": "Developed a non-intrusive behavioral biometric system that analyzes mouse movement patterns to identify anomalous behavior without compromising user privacy or requiring additional hardware.",
    "projects.project1.results": "The system achieved 92% accuracy in detecting fraudulent behavior with a false positive rate of only 3%, significantly improving assessment integrity while maintaining a positive user experience.",
    "projects.project2.title": "Mouse Dynamics Biometric Fraud Detection System using Deep Learning",
    "projects.project2.period": "May 2024 - Nov 2024",
    "projects.project2.description": "Developed a fraud detection system using mouse dynamics and deep learning to enhance the security of online assessments.",
    "projects.project2.achievement1": "Implemented data preprocessing pipelines achieving 100% data usability",
    "projects.project2.achievement2": "Engineered 12 optimized feature sets using advanced selection methods",
    "projects.project2.achievement3": "Developed and tested multiple deep learning models (ANN, LSTM, LSTM-CNN, LSTM-Transformer)",
    "projects.project2.achievement4": "Built data visualization tools to monitor system performance",
    "projects.project2.achievement5": "Exceeded project goals, achieving 95% detection accuracy and a false negative rate below 5%",
    "projects.project2.challenge": "Existing fraud detection systems struggled with real-time analysis and had high computational requirements, making them impractical for widespread implementation.",
    "projects.project2.approach": "Leveraged deep learning architectures to create a lightweight, efficient system capable of real-time analysis with minimal computational overhead, focusing on optimizing both accuracy and performance.",
    "projects.project2.results": "The system processed user behavior in real-time with a latency of less than 200ms, while maintaining 95% detection accuracy and reducing computational requirements by 60% compared to previous solutions.",
    "projects.project3.title": "Continuous Authentication with Behavioral Biometrics",
    "projects.project3.period": "May 2024 - Nov 2024",
    "projects.project3.description": "Conducted a literature review on the use of behavioral biometrics, specifically mouse dynamics and keystroke analysis, for continuous user authentication.",
    "projects.project3.achievement1": "Researched current methods, challenges, and potential improvements in the field",
    "projects.project3.achievement2": "Identified key research gaps and proposed a novel authentication method using real-time behavioral biometric information security (RBBIS)",
    "projects.project3.achievement3": "Developed a research framework and work plan for implementing and evaluating the proposed method",
    "projects.project3.challenge": "Traditional authentication methods rely on one-time verification, creating security vulnerabilities once a user is logged in, while continuous methods often create friction in the user experience.",
    "projects.project3.approach": "Developed a framework for passive, continuous authentication that monitors behavioral patterns in the background without interrupting the user's workflow, adapting to changing user behavior over time.",
    "projects.project3.results": "The proposed framework demonstrated the potential to reduce unauthorized access incidents by up to 87% in simulated environments, while maintaining a seamless user experience with no additional authentication prompts.",
    
    // Services
    "services.title": "My Services",
    "services.web": "Web Application Development",
    "services.web.desc": "Custom web applications built with React and Next.js, focusing on performance and user experience.",
    "services.backend": "Backend Development",
    "services.backend.desc": "Robust and scalable server-side solutions using Node.js, Express, and Fastify.",
    "services.api": "API Development",
    "services.api.desc": "RESTful and GraphQL API design and implementation for seamless data flow between client and server.",
    "services.responsive": "Responsive Design",
    "services.responsive.desc": "Mobile-first, responsive web designs that work flawlessly across all devices and screen sizes.",
    
    // Education
    "education.title": "Education & Certifications",
    "education.master": "Master of Information Technology (Business Informatics)",
    "education.master.institution": "James Cook University Singapore",
    "education.master.period": "Mar 2024 – Apr 2025",
    "education.master.achievement1": "Specializing in data analytics and business intelligence",
    "education.master.achievement2": "Conducting research in behavioral biometrics and fraud detection",
    "education.master.achievement3": "Developing advanced machine learning models for security applications",
    "education.bachelor": "Bachelor of Information Technology",
    "education.bachelor.institution": "James Cook University Singapore",
    "education.bachelor.period": "Nov 2022 – Feb 2024",
    "education.bachelor.achievement1": "Focused on software development and system design",
    "education.bachelor.achievement2": "Completed projects in user interface design and application development",
    "education.bachelor.achievement3": "Gained expertise in multiple programming languages and frameworks",
    "education.bachelor.achievement4": "Conferred on March 7, 2024 with a GPA of 5.27",
    "education.diploma": "Higher National Diploma of Software Engineering (Level 5)",
    "education.diploma.institution": "INET IT ACADEMY",
    "education.diploma.period": "Mar 2018 – Oct 2022",
    "education.diploma.achievement1": "Developed foundational knowledge in software engineering principles",
    "education.diploma.achievement2": "Completed practical projects in application development",
    "education.diploma.achievement3": "Learned system analysis and design methodologies",
    "education.achievements": "Key Achievements",
    "education.certifications": "Certifications & Testamurs",
    "education.verification": "Verification Details",
    "education.cert1.title": "Bachelor of Information Technology",
    "education.cert1.issuer": "James Cook University Singapore",
    "education.cert1.date": "March 7, 2024",
    "education.cert1.description": "Official testamur for the Bachelor of Information Technology degree, conferred on March 7, 2024. The degree provides a comprehensive foundation in information technology concepts, programming, database design, and system development.",
    "education.cert1.verificationMessage": "Verification details are not available for this testamur.",
    "education.cert2.title": "The Fundamentals of Digital Marketing",
    "education.cert2.issuer": "Google Digital Garage",
    "education.cert2.date": "April 3, 2023",
    "education.cert2.description": "Comprehensive certification covering digital marketing fundamentals, including search engine optimization, social media marketing, and analytics.",
    "education.cert3.title": "Google Data Analytics",
    "education.cert3.issuer": "Google",
    "education.cert3.date": "2023",
    "education.cert3.description": "Professional certification covering data analysis, visualization, and interpretation using Google's analytics tools.",
    "education.verifyAuthenticity": "Verify the authenticity of this certificate at:",
    "education.certificateId": "Certificate ID:",
    "education.verificationInfo": "Verification Information",
    "education.verifyButton": "Verify Certificate",
    
    // Contact
    "contact.title": "Get in Touch",
    "contact.info": "Contact Information",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.connect": "Connect With Me",
    "contact.connect.desc": "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision.",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.send": "Send Message",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Thank you! Your message has been sent successfully. I'll get back to you soon.",
    "contact.form.error": "Failed to submit form. Please try again.",
    "contact.form.nameRequired": "Name must be at least 2 characters",
    "contact.form.emailRequired": "Please enter a valid email address",
    "contact.form.subjectRequired": "Subject must be at least 5 characters",
    "contact.form.messageRequired": "Message must be at least 10 characters",
    
    // Testimonials
    "testimonials.title": "Client Testimonials",
    "testimonials.prev": "Previous testimonial",
    "testimonials.next": "Next testimonial",
    "testimonials.goto": "Go to testimonial {number}",
    "testimonials.client1.quote": "Kaung's expertise in developing our POS system transformed our business operations. His attention to detail and problem-solving skills are exceptional.",
    "testimonials.client1.name": "Sarah Chen",
    "testimonials.client1.title": "Operations Manager, RetailTech Solutions",
    "testimonials.client2.quote": "Working with Kaung on our fraud detection system was a game-changer. His deep understanding of behavioral biometrics and machine learning delivered results beyond our expectations.",
    "testimonials.client2.name": "Michael Rodriguez",
    "testimonials.client2.title": "CTO, SecureFinance",
    "testimonials.client3.quote": "Kaung's ability to translate complex technical requirements into user-friendly solutions is remarkable. His work on our network infrastructure significantly improved our system stability.",
    "testimonials.client3.name": "Priya Sharma",
    "testimonials.client3.title": "IT Director, Global Connect",

    // System Monitor
    "systemMonitor.title": "System Monitor",
    "systemMonitor.systemTime": "System Time",
    "systemMonitor.cpuUsage": "CPU Usage",
    "systemMonitor.memoryUsage": "Memory Usage",
    "systemMonitor.networkActivity": "Network Activity",
    "systemMonitor.skillsMonitor": "Skills Monitor",
    "systemMonitor.show": "Show Interface",
    "systemMonitor.hide": "Hide Interface",

    // Terminal
    "terminal.title": "KSL DevConsole",
    "terminal.welcome": "Welcome to Kaung Sithu Linn's portfolio. Type 'help' to see available commands.",
    "terminal.help": "Available commands",
    "terminal.about": "About",
    "terminal.skills": "Skills",
    "terminal.projects": "Projects",
    "terminal.contact": "Contact",
    "terminal.experience": "Experience",
    "terminal.education": "Education",
    "terminal.clear": "Clear the terminal",
    "terminal.exit": "Exit terminal mode",
    "terminal.askAI": "Ask the AI assistant",

    // File Explorer
    "fileExplorer.title": "Portfolio Explorer",
    "fileExplorer.projects": "Projects",
    "fileExplorer.resume": "Resume",
    "fileExplorer.certificates": "Certificates",
    "fileExplorer.mainPython": "Main Python script for the fraud detection system",
    "fileExplorer.model": "Trained machine learning model",
    "fileExplorer.readme": "Project documentation",
    "fileExplorer.authSystem": "Authentication system implementation",
    "fileExplorer.researchPaper": "Research paper on behavioral biometrics",
    "fileExplorer.currentResume": "Current professional resume",
    "fileExplorer.profilePhoto": "Professional headshot",
    "fileExplorer.bachelorCert": "Bachelor of Information Technology degree certificate",
    "fileExplorer.googleCert": "Google Digital Marketing certification",
  },
  zh: {
    // Common
    "common.language": "语言",
    "common.english": "English",
    "common.chinese": "中文",
    "common.malay": "Bahasa Melayu",
    "common.tamil": "தமிழ்",
    "common.arabic": "العربية",
    "common.learnMore": "了解更多",
    "common.contactMe": "联系我",
    "common.downloadResume": "下载简历",
    "common.resume": "简历",
    "common.scrollTo": "滚动到{section}",
    "common.loading": "加载中...",
    "common.close": "关闭",
    "common.open": "打开",
    "common.view": "查看",
    "common.hide": "隐藏",
    "common.show": "显示",
    "common.back": "返回",
    "common.next": "下一个",
    "common.previous": "上一个",
    "common.submit": "提交",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.all": "全部",
    "common.none": "无",
    "common.yes": "是",
    "common.no": "否",
    "common.success": "成功",
    "common.error": "错误",
    "common.warning": "警告",
    "common.info": "信息",

    // Navigation
    "nav.home": "首页",
    "nav.about": "关于",
    "nav.experience": "经验",
    "nav.skills": "技能",
    "nav.projects": "项目",
    "nav.services": "服务",
    "nav.testimonials": "推荐",
    "nav.education": "教育",
    "nav.contact": "联系",
    "nav.scrollTo": "滚动到{section}",

    // Hero
    "hero.tagline": "打造数字解决方案",
    "hero.title": "Kaung Sithu Linn",
    "hero.subtitle": "软件开发工程师",
    "hero.jobTitle": "软件开发工程师",
    "hero.description": "拥有4年以上经验的软件开发人员，专注于创建直观的用户界面，进行全面测试，并提供满足复杂需求的高质量应用程序。专长于POS系统、欺诈检测和行为生物识别。",
    "hero.githubProfile": "GitHub 主页",
    "hero.linkedinProfile": "LinkedIn 主页",
    "hero.emailContact": "电子邮件联系",
    "hero.portfolioWebsite": "作品集网站",
    "hero.downloadResume": "下载简历",
    "hero.resume": "简历",
    "hero.learnMore": "了解更多",
    "hero.contactMe": "联系我",
    "hero.profileImageAlt": "Kaung Sithu Linn - 软件开发工程师",

    // About
    "about.title": "关于我",
    "about.paragraph1": "作为一名热情的软件开发人员，我专注于开发稳健的应用程序，注重用户体验和系统优化。在eVolva Software House工作超过4年，我通过创新的POS系统和网络解决方案改变了业务运营。",
    "about.paragraph2": "我最近的研究专注于使用机器学习的前沿行为生物识别和欺诈检测。我还获得了数字营销基础认证，使我能够将技术开发与有效的市场策略相结合。我目前正在新加坡詹姆斯库克大学攻读信息技术硕士学位，主修商业信息学，继续扩展我在数据分析和人工智能应用方面的专业知识。",
    "about.quote": "我相信创造的技术不仅能解决问题，还能提升人类体验。我的目标是构建安全、高效、用户友好的解决方案，带来真正的改变。",
    "about.decorativeImageAlt": "装饰背景",
    "about.skills.frontend.title": "前端",
    "about.skills.frontend.description": "JavaScript, HTML5, CSS, 用户界面设计",
    "about.skills.backend.title": "后端",
    "about.skills.backend.description": "Python, Java, C++, .NET",
    "about.skills.database.title": "数据库",
    "about.skills.database.description": "SQL, 数据管理",
    "about.skills.ai.title": "人工智能/机器学习",
    "about.skills.ai.description": "行为生物识别, 深度学习",
    "about.skills.marketing.title": "数字营销",
    "about.skills.marketing.description": "搜索引擎优化, 分析, 内容策略",
    "about.skills.languages.title": "语言",
    "about.skills.languages.description": "英语, 缅甸语, 中文, 日语",
    
    // Header
    "header.about": "关于",
    "header.experience": "经验",
    "header.skills": "技能",
    "header.services": "服务",
    "header.education": "教育",
    "header.contact": "联系",
    
    // Skills
    "skills.title": "技能与专长",
    "skills.frontend": "前端开发",
    "skills.frontend.tech": "JavaScript, HTML5, CSS",
    "skills.frontend.desc": "使用现代Web技术构建响应式和交互式用户界面。",
    "skills.backend": "后端开发",
    "skills.backend.tech": "Python, Java, C++, .NET",
    "skills.backend.desc": "创建注重性能和可靠性的强大服务器端应用程序。",
    "skills.database": "数据库管理",
    "skills.database.tech": "SQL, 数据管理",
    "skills.database.desc": "设计和实现高效的数据库架构和查询，实现最佳数据管理。",
    "skills.uiux": "UI/UX设计",
    "skills.uiux.tech": "用户界面设计",
    "skills.uiux.desc": "打造注重可用性和可访问性的直观用户界面。",
    "skills.ml": "机器学习",
    "skills.ml.tech": "行为生物识别, 深度学习",
    "skills.ml.desc": "开发用于欺诈检测和用户认证的行为模式机器学习模型。",
    "skills.programming": "编程语言",
    "skills.programming.tech": "JavaScript, Python, Java, C++",
    "skills.programming.desc": "在多种编程语言中编写高效代码，适用于各种应用。",
    "skills.multilingual": "多语言能力",
    "skills.multilingual.tech": "英语, 缅甸语, 中文, 日语",
    "skills.multilingual.desc": "在多种语言中有效沟通，促进国际合作。",
    "skills.communication": "沟通能力",
    "skills.communication.tech": "技术写作, 公开演讲",
    "skills.communication.desc": "向技术和非技术受众清晰传达复杂的技术概念。",
    "skills.optimization": "系统优化",
    "skills.optimization.tech": "性能调优, 网络解决方案",
    "skills.optimization.desc": "提升系统性能并解决复杂技术问题，实现最佳运行。",
    "skills.research": "研究能力",
    "skills.research.tech": "学术研究, 文献综述",
    "skills.research.desc": "进行深入研究，识别差距并在技术领域提出创新解决方案。",

    // Experience
    "experience.title": "专业经验",
    "experience.company": "eVolva Software House",
    "experience.location": "缅甸曼德勒",
    "experience.period": "2018年12月至今",
    "experience.role": "软件开发人员和客户测试员",
    "experience.responsibilities.1": "使用Microsoft .NET设计和开发POS系统，简化库存管理，提高运营效率",
    "experience.responsibilities.2": "将过时的Microsoft Access（Office 2003）POS系统升级为现代SQL独立应用程序，提升性能",
    "experience.responsibilities.3": "通过实施自定义隧道解决方案解决VPN网络的LAN干扰问题，确保连接稳定",
    "experience.responsibilities.4": "提供优化的POS系统，将商店效率提高50%以上，减少交易时间并改进库存跟踪",
    "experience.responsibilities.5": "进行全面测试和客户培训，确保新系统的无缝采用",
    "experience.decorativeImageAlt": "装饰背景",
    "experience.keyAchievements": "主要成就",
    
    // Projects
    "projects.title": "精选项目",
    "projects.viewProject": "查看项目",
    "projects.hideCase": "隐藏案例研究",
    "projects.viewCase": "查看案例研究",
    "projects.challenge": "挑战",
    "projects.approach": "方法",
    "projects.results": "结果",
    "projects.technologies": "使用的技术",
    "projects.project1.title": "在线评估欺诈检测的鼠标动态分析",
    "projects.project1.period": "2024年5月 - 2024年11月",
    "projects.project1.description": "开发了一个机器学习模型，使用鼠标动态作为行为生物识别来检测在线评估中的欺诈行为。",
    "projects.project1.achievement1": "分析鼠标移动和点击模式，创建用户配置文件并识别表明欺诈的异常",
    "projects.project1.achievement2": "实施特征选择技术并评估多个机器学习模型，在欺诈检测中实现高准确度",
    "projects.project1.achievement3": "识别对用户认证最具辨别力的关键鼠标动态特征",
    "projects.project1.challenge": "教育机构面临在线评估作弊事件增加的问题，传统监考方法无法检测复杂的欺诈技术。",
    "projects.project1.approach": "开发了一种非侵入式行为生物识别系统，分析鼠标移动模式以识别异常行为，无需损害用户隐私或额外硬件。",
    "projects.project1.results": "该系统在检测欺诈行为方面达到92%的准确率，误报率仅为3%，显著提高了评估完整性，同时保持了良好的用户体验。",
    "projects.project2.title": "使用深度学习的鼠标动态生物识别欺诈检测系统",
    "projects.project2.period": "2024年5月 - 2024年11月",
    "projects.project2.description": "开发了一个使用鼠标动态和深度学习的欺诈检测系统，增强在线评估的安全性。",
    "projects.project2.achievement1": "实施数据预处理管道，实现100%的数据可用性",
    "projects.project2.achievement2": "使用高级选择方法设计了12个优化特征集",
    "projects.project2.achievement3": "开发并测试了多个深度学习模型（ANN、LSTM、LSTM-CNN、LSTM-Transformer）",
    "projects.project2.achievement4": "构建数据可视化工具监控系统性能",
    "projects.project2.achievement5": "超越项目目标，实现95%的检测准确率和低于5%的假阴性率",
    "projects.project2.challenge": "现有欺诈检测系统难以进行实时分析，且计算需求高，使其难以广泛实施。",
    "projects.project2.approach": "利用深度学习架构创建轻量级、高效的系统，能够以最小的计算开销进行实时分析，专注于优化准确性和性能。",
    "projects.project2.results": "该系统以不到200毫秒的延迟实时处理用户行为，同时保持95%的检测准确率，与之前的解决方案相比，计算需求减少了60%。",
    "projects.project3.title": "使用行为生物识别的持续认证",
    "projects.project3.period": "2024年5月 - 2024年11月",
    "projects.project3.description": "对使用行为生物识别，特别是鼠标动态和击键分析进行持续用户认证的文献综述。",
    "projects.project3.achievement1": "研究了该领域的当前方法、挑战和潜在改进",
    "projects.project3.achievement2": "识别关键研究差距并提出使用实时行为生物识别信息安全（RBBIS）的新型认证方法",
    "projects.project3.achievement3": "开发了实施和评估所提方法的研究框架和工作计划",
    "projects.project3.challenge": "传统认证方法依赖一次性验证，一旦用户登录就会产生安全漏洞，而持续方法往往会在用户体验中造成摩擦。",
    "projects.project3.approach": "开发了一个被动、持续认证的框架，在后台监控行为模式，不中断用户的工作流程，适应随时间变化的用户行为。",
    "projects.project3.results": "所提框架在模拟环境中展示了将未授权访问事件减少高达87%的潜力，同时保持无缝用户体验，无需额外认证提示。",
    
    // Services
    "services.title": "我的服务",
    "services.web": "Web应用程序开发",
    "services.web.desc": "使用React和Next.js构建的自定义Web应用程序，注重性能和用户体验。",
    "services.backend": "后端开发",
    "services.backend.desc": "使用Node.js、Express和Fastify的强大可扩展服务器端解决方案。",
    "services.api": "API开发",
    "services.api.desc": "RESTful和GraphQL API设计和实现，实现客户端和服务器之间的无缝数据流。",
    "services.responsive": "响应式设计",
    "services.responsive.desc": "移动优先的响应式Web设计，在所有设备和屏幕尺寸上完美运行。",
    
    // Education
    "education.title": "教育与认证",
    "education.master": "信息技术硕士（商业信息学）",
    "education.master.institution": "新加坡詹姆斯库克大学",
    "education.master.period": "2024年3月 – 2025年4月",
    "education.master.achievement1": "专注于数据分析和商业智能",
    "education.master.achievement2": "进行行为生物识别和欺诈检测研究",
    "education.master.achievement3": "开发用于安全应用的高级机器学习模型",
    "education.bachelor": "信息技术学士",
    "education.bachelor.institution": "新加坡詹姆斯库克大学",
    "education.bachelor.period": "2022年11月 – 2024年2月",
    "education.bachelor.achievement1": "专注于软件开发和系统设计",
    "education.bachelor.achievement2": "完成用户界面设计和应用程序开发项目",
    "education.bachelor.achievement3": "获得多种编程语言和框架的专业知识",
    "education.bachelor.achievement4": "2024年3月7日授予学位，GPA为5.27",
    "education.diploma": "软件工程高级国家文凭（5级）",
    "education.diploma.institution": "INET IT学院",
    "education.diploma.period": "2018年3月 – 2022年10月",
    "education.diploma.achievement1": "发展软件工程原理的基础知识",
    "education.diploma.achievement2": "完成应用程序开发的实践项目",
    "education.diploma.achievement3": "学习系统分析和设计方法",
    "education.achievements": "主要成就",
    "education.certifications": "证书与学位证明",
    "education.verification": "验证详情",
    "education.cert1.title": "信息技术学士",
    "education.cert1.issuer": "新加坡詹姆斯库克大学",
    "education.cert1.date": "2024年3月7日",
    "education.cert1.description": "信息技术学士学位的官方证明，于2024年3月7日授予。该学位为信息技术概念、编程、数据库设计和系统开发提供了全面的基础。",
    "education.cert1.verificationMessage": "此证明没有可用的验证详情。",
    "education.cert2.title": "数字营销基础",
    "education.cert2.issuer": "Google数字车库",
    "education.cert2.date": "2023年4月3日",
    "education.cert2.description": "全面的认证，涵盖数字营销基础，包括搜索引擎优化、社交媒体营销和分析。",
    "education.cert3.title": "Google数据分析",
    "education.cert3.issuer": "Google",
    "education.cert3.date": "2023年",
    "education.cert3.description": "专业认证，涵盖使用Google分析工具进行数据分析、可视化和解释。",
    "education.verifyAuthenticity": "在以下位置验证此证书的真实性：",
    "education.certificateId": "证书ID：",
    "education.verificationInfo": "验证信息",
    "education.verifyButton": "验证证书",
    
    // Contact
    "contact.title": "联系我",
    "contact.info": "联系信息",
    "contact.email": "电子邮件",
    "contact.phone": "电话",
    "contact.address": "地址",
    "contact.connect": "与我联系",
    "contact.connect.desc": "我随时欢迎讨论新项目、创意想法或成为您愿景一部分的机会。",
    "contact.form.name": "姓名",
    "contact.form.email": "电子邮件",
    "contact.form.subject": "主题",
    "contact.form.message": "消息",
    "contact.form.send": "发送消息",
    "contact.form.sending": "发送中...",
    "contact.form.success": "谢谢！您的消息已成功发送。我会尽快回复您。",
    "contact.form.error": "提交表单失败。请重试。",
    "contact.form.nameRequired": "姓名必须至少有2个字符",
    "contact.form.emailRequired": "请输入有效的电子邮件地址",
    "contact.form.subjectRequired": "主题必须至少有5个字符",
    "contact.form.messageRequired": "消息必须至少有10个字符",
    
    // Testimonials
    "testimonials.title": "客户推荐",
    "testimonials.prev": "上一个推荐",
    "testimonials.next": "下一个推荐",
    "testimonials.goto": "前往推荐{number}",
    "testimonials.client1.quote": "Kaung在开发我们的POS系统方面的专业知识改变了我们的业务运营。他的注重细节和解决问题的能力非常出色。",
    "testimonials.client1.name": "Sarah Chen",
    "testimonials.client1.title": "RetailTech Solutions运营经理",
    "testimonials.client2.quote": "与Kaung合作开发我们的欺诈检测系统是一个改变游戏规则的经历。他对行为生物识别和机器学习的深刻理解带来了超出我们预期的结果。",
    "testimonials.client2.name": "Michael Rodriguez",
    "testimonials.client2.title": "SecureFinance首席技术官",
    "testimonials.client3.quote": "Kaung将复杂的技术需求转化为用户友好解决方案的能力非常出色。他对我们网络基础设施的工作显著提高了我们的系统稳定性。",
    "testimonials.client3.name": "Priya Sharma",
    "testimonials.client3.title": "Global Connect IT总监",

    // System Monitor
    "systemMonitor.title": "系统监控",
    "systemMonitor.systemTime": "系统时间",
    "systemMonitor.cpuUsage": "CPU 使用率",
    "systemMonitor.memoryUsage": "内存使用率",
    "systemMonitor.networkActivity": "网络活动",
    "systemMonitor.skillsMonitor": "技能监控",
    "systemMonitor.show": "显示界面",
    "systemMonitor.hide": "隐藏界面",

    // Terminal
    "terminal.title": "KSL 开发控制台",
    "terminal.welcome": "欢迎来到 Kaung Sithu Linn 的作品集。输入 'help' 查看可用命令。",
    "terminal.help": "可用命令",
    "terminal.about": "关于",
    "terminal.skills": "技能",
    "terminal.projects": "项目",
    "terminal.contact": "联系",
    "terminal.experience": "经验",
    "terminal.education": "教育",
    "terminal.clear": "清除终端",
    "terminal.exit": "退出终端模式",
    "terminal.askAI": "询问AI助手",

    // File Explorer
    "fileExplorer.title": "作品集浏览器",
    "fileExplorer.projects": "项目",
    "fileExplorer.resume": "简历",
    "fileExplorer.certificates": "证书",
    "fileExplorer.mainPython": "欺诈检测系统的主要Python脚本",
    "fileExplorer.model": "训练好的机器学习模型",
    "fileExplorer.readme": "项目文档",
    "fileExplorer.authSystem": "认证系统实现",
    "fileExplorer.researchPaper": "关于行为生物识别的研究论文",
    "fileExplorer.currentResume": "当前专业简历",
    "fileExplorer.profilePhoto": "专业头像",
    "fileExplorer.bachelorCert": "信息技术学士学位证书",
    "fileExplorer.googleCert": "Google数字营销认证",
  },
  ms: {
    // Common
    "common.language": "Bahasa",
    "common.english": "English",
    "common.chinese": "中文",
    "common.malay": "Bahasa Melayu",
    "common.tamil": "தமிழ்",
    "common.arabic": "العربية",
    "common.learnMore": "Ketahui Lebih Lanjut",
    "common.contactMe": "Hubungi Saya",
    "common.downloadResume": "Muat Turun Resume",
    "common.resume": "Resume",
    "common.scrollTo": "Skrol ke {section}",
    "common.loading": "Memuatkan...",
    "common.close": "Tutup",
    "common.open": "Buka",
    "common.view": "Lihat",
    "common.hide": "Sembunyikan",
    "common.show": "Tunjukkan",
    "common.back": "Kembali",
    "common.next": "Seterusnya",
    "common.previous": "Sebelumnya",
    "common.submit": "Hantar",
    "common.cancel": "Batal",
    "common.save": "Simpan",
    "common.delete": "Padam",
    "common.edit": "Edit",
    "common.search": "Cari",
    "common.filter": "Tapis",
    "common.sort": "Susun",
    "common.all": "Semua",
    "common.none": "Tiada",
    "common.yes": "Ya",
    "common.no": "Tidak",
    "common.success": "Berjaya",
    "common.error": "Ralat",
    "common.warning": "Amaran",
    "common.info": "Maklumat",

    // Navigation
    "nav.home": "Laman Utama",
    "nav.about": "Tentang",
    "nav.experience": "Pengalaman",
    "nav.skills": "Kemahiran",
    "nav.projects": "Projek",
    "nav.services": "Perkhidmatan",
    "nav.testimonials": "Testimoni",
    "nav.education": "Pendidikan",
    "nav.contact": "Hubungi",
    "nav.scrollTo": "Skrol ke {section}",

    // Hero
    "hero.tagline": "Mencipta Penyelesaian Digital",
    "hero.title": "Kaung Sithu Linn",
    "hero.subtitle": "Pembangun Perisian",
    "hero.jobTitle": "Pembangun Perisian",
    "hero.description": "Pembangun yang berpengalaman lebih dari 4 tahun dalam mencipta antara muka pengguna yang intuitif, menjalankan ujian menyeluruh, dan menyampaikan aplikasi berkualiti tinggi yang memenuhi keperluan kompleks. Pakar dalam sistem POS, pengesanan penipuan, dan biometrik tingkah laku.",
    "hero.githubProfile": "Profil GitHub",
    "hero.linkedinProfile": "Profil LinkedIn",
    "hero.emailContact": "Hubungi Emel",
    "hero.portfolioWebsite": "Laman Web Portfolio",
    "hero.downloadResume": "Muat Turun Resume",
    "hero.resume": "Resume",
    "hero.learnMore": "Ketahui Lebih Lanjut",
    "hero.contactMe": "Hubungi Saya",
    "hero.profileImageAlt": "Kaung Sithu Linn - Pembangun Perisian",

    // About
    "about.title": "Tentang Saya",
    "about.paragraph1": "Sebagai Pembangun Perisian yang bersemangat di Singapura, saya pakar dalam membangunkan aplikasi yang teguh dengan fokus pada pengalaman pengguna dan pengoptimuman sistem. Dengan lebih dari 4 tahun di eVolva Software House, saya telah mengubah operasi perniagaan melalui sistem POS dan penyelesaian rangkaian yang inovatif.",
    "about.paragraph2": "Penyelidikan terkini saya fokus pada biometrik tingkah laku dan pengesanan penipuan menggunakan pembelajaran mesin. Saya juga mempunyai sijil dalam asas pemasaran digital, membolehkan saya menghubungkan pembangunan teknikal dengan strategi pasaran yang berkesan. Saya kini sedang mengejar Sarjana dalam Teknologi Maklumat dengan pengkhususan dalam Informatik Perniagaan di James Cook University Singapore, di mana saya terus mengembangkan kepakaran saya dalam analisis data dan aplikasi AI.",
    "about.quote": "Saya percaya dalam mencipta teknologi yang bukan sahaja menyelesaikan masalah tetapi meningkatkan pengalaman manusia. Matlamat saya adalah untuk membina penyelesaian yang selamat, cekap, dan mesra pengguna yang membuat perbezaan sebenar.",
    "about.decorativeImageAlt": "Latar belakang hiasan",
    "about.skills.frontend.title": "Frontend",
    "about.skills.frontend.description": "JavaScript, HTML5, CSS, Reka Bentuk UI",
    "about.skills.backend.title": "Backend",
    "about.skills.backend.description": "Python, Java, C++, .NET",
    "about.skills.database.title": "Pangkalan Data",
    "about.skills.database.description": "SQL, Pengurusan Data",
    "about.skills.ai.title": "AI/ML",
    "about.skills.ai.description": "Biometrik Tingkah Laku, Pembelajaran Mendalam",
    "about.skills.marketing.title": "Pemasaran Digital",
    "about.skills.marketing.description": "SEO, Analitik, Strategi Kandungan",
    "about.skills.languages.title": "Bahasa",
    "about.skills.languages.description": "Bahasa Inggeris, Burma, Cina, Jepun",
    
    // Header
    "header.about": "Tentang",
    "header.experience": "Pengalaman",
    "header.skills": "Kemahiran",
    "header.services": "Perkhidmatan",
    "header.education": "Pendidikan",
    "header.contact": "Hubungi",
    
    // Skills
    "skills.title": "Kemahiran & Kepakaran",
    "skills.frontend": "Pembangunan Frontend",
    "skills.frontend.tech": "JavaScript, HTML5, CSS",
    "skills.frontend.desc": "Membina antara muka pengguna yang responsif dan interaktif dengan teknologi web moden.",
    "skills.backend": "Pembangunan Backend",
    "skills.backend.tech": "Python, Java, C++, .NET",
    "skills.backend.desc": "Mencipta aplikasi pelayan yang teguh dengan fokus pada prestasi dan kebolehpercayaan.",
    "skills.database": "Pengurusan Pangkalan Data",
    "skills.database.tech": "SQL, Pengurusan Data",
    "skills.database.desc": "Merancang dan melaksanakan skema dan pertanyaan pangkalan data yang cekap untuk pengurusan data yang optimum.",
    "skills.uiux": "Reka Bentuk UI/UX",
    "skills.uiux.tech": "Reka Bentuk Antara Muka Pengguna",
    "skills.uiux.desc": "Mencipta antara muka pengguna yang intuitif dengan fokus pada kebolehgunaan和 kebolehcapaian。",
    "skills.ml": "Pembelajaran Mesin",
    "skills.ml.tech": "Biometrik Tingkah Laku, Pembelajaran Mendalam",
    "skills.ml.desc": "Membangunkan model ML untuk pengesanan penipuan dan pengesahan pengguna menggunakan corak tingkah laku。",
    "skills.programming": "Bahasa Pengaturcaraan",
    "skills.programming.tech": "JavaScript, Python, Java, C++",
    "skills.programming.desc": "Menulis kod yang cekap dalam pelbagai bahasa pengaturcaraan untuk aplikasi yang pelbagai。",
    "skills.multilingual": "Berbilang Bahasa",
    "skills.multilingual.tech": "Bahasa Inggeris, Burma, Cina, Jepun",
    "skills.multilingual.desc": "Berkomunikasi secara berkesan dalam pelbagai bahasa untuk kerjasama antarabangsa",
    "skills.communication": "Komunikasi",
    "skills.communication.tech": "Penulisan Teknikal, Pengucapan Awam",
    "skills.communication.desc": "Menyampaikan konsep teknikal yang kompleks dengan jelas kepada kedua-dua penonton teknikal dan bukan teknikal。",
    "skills.optimization": "Pengoptimuman Sistem",
    "skills.optimization.tech": "Penalaan Prestasi, Penyelesaian Rangkaian",
    "skills.optimization.desc": "Meningkatkan prestasi sistem dan menyelesaikan masalah teknikal yang kompleks untuk operasi yang optimum。",
    "skills.research": "Penyelidikan",
    "skills.research.tech": "Penyelidikan Akademik, Kajian Literatur",
    "skills.research.desc": "Menjalankan penyelidikan yang menyeluruh untuk mengenal pasti jurang dan mencadangkan penyelesaian inovatif dalam teknologi。",

    // Experience
    "experience.title": "Pengalaman Profesional",
    "experience.company": "eVolva Software House",
    "experience.location": "Mandalay, Myanmar",
    "experience.period": "Dis 2018 - Kini",
    "experience.role": "Pembangun Perisian dan Penguji Pelanggan",
    "experience.responsibilities.1": "Mereka bentuk dan membangunkan sistem POS menggunakan Microsoft .NET untuk menyelaraskan pengurusan stok dan inventori, meningkatkan kecekapan operasi",
    "experience.responsibilities.2": "Menaik taraf sistem POS Microsoft Access (Office 2003) yang lapuk kepada aplikasi kendiri SQL moden, meningkatkan prestasi",
    "experience.responsibilities.3": "Menyelesaikan isu gangguan LAN dengan rangkaian VPN dengan melaksanakan penyelesaian terowong tersuai, memastikan sambungan stabil",
    "experience.responsibilities.4": "Menyampaikan sistem POS yang dioptimumkan yang meningkatkan kecekapan kedai lebih daripada 50%, mengurangkan masa transaksi dan meningkatkan penjejakan inventori",
    "experience.responsibilities.5": "Menjalankan ujian menyeluruh dan latihan pelanggan untuk memastikan penggunaan sistem baharu yang lancar",
    "experience.decorativeImageAlt": "Latar belakang hiasan",
    "experience.keyAchievements": "Pencapaian Utama",
    
    // Projects
    "projects.title": "Projek Pilihan",
    "projects.viewProject": "Lihat Projek",
    "projects.hideCase": "Sembunyikan Kajian Kes",
    "projects.viewCase": "Lihat Kajian Kes",
    "projects.challenge": "Cabaran",
    "projects.approach": "Pendekatan",
    "projects.results": "Keputusan",
    "projects.technologies": "Teknologi Digunakan",
    "projects.project1.title": "Dinamik Tetikus untuk Pengesanan Penipuan Penilaian Dalam Talian",
    "projects.project1.period": "Mei 2024 - Nov 2024",
    "projects.project1.description": "Membangunkan model pembelajaran mesin untuk mengesan tingkah laku penipuan semasa penilaian dalam talian menggunakan dinamik tetikus sebagai biometrik tingkah laku。",
    "projects.project1.achievement1": "Menganalisis pergerakan tetikus dan corak klik untuk mencipta profil pengguna dan mengenal pasti anomali yang menunjukkan penipuan",
    "projects.project1.achievement2": "Melaksanakan teknik pemilihan ciri dan menilai pelbagai model pembelajaran mesin, mencapai ketepatan tinggi dalam pengesanan penipuan",
    "projects.project1.achievement3": "Mengenal pasti ciri dinamik tetikus utama yang paling diskriminatif untuk pengesahan pengguna",
    "projects.project1.challenge": "Institusi pendidikan menghadapi peningkatan insiden penipuan dalam penilaian dalam talian, dengan kaedah proctoring tradisional terbukti tidak mencukupi untuk mengesan teknik penipuan yang canggih。",
    "projects.project1.approach": "Membangunkan sistem biometrik tingkah laku yang tidak mengganggu yang menganalisis corak pergerakan tetikus untuk mengenal pasti tingkah laku anomali tanpa menjejaskan privasi pengguna atau memerlukan perkakasan tambahan。",
    "projects.project1.results": "Sistem ini mencapai ketepatan 92% dalam mengesan tingkah laku penipuan dengan kadar positif palsu hanya 3%, meningkatkan integriti penilaian dengan ketara sambil mengekalkan pengalaman pengguna yang positif。",
    "projects.project2.title": "Sistem Pengesanan Penipuan Biometrik Dinamik Tetikus menggunakan Pembelajaran Mendalam",
    "projects.project2.period": "Mei 2024 - Nov 2024",
    "projects.project2.description": "Membangunkan sistem pengesanan penipuan menggunakan dinamik tetikus dan pembelajaran mendalam untuk meningkatkan keselamatan penilaian dalam talian。",
    "projects.project2.achievement1": "Melaksanakan saluran paip prapemprosesan data mencapai kebolehgunaan data 100%",
    "projects.project2.achievement2": "Mereka bentuk 12 set ciri yang dioptimumkan menggunakan kaedah pemilihan lanjutan",
    "projects.project2.achievement3": "Membangunkan dan menguji pelbagai model pembelajaran mendalam (ANN, LSTM, LSTM-CNN, LSTM-Transformer)",
    "projects.project2.achievement4": "Membina alat visualisasi data untuk memantau prestasi sistem",
    "projects.project2.achievement5": "Melebihi matlamat projek, mencapai ketepatan pengesanan 95% dan kadar negatif palsu di bawah 5%",
    "projects.project2.challenge": "Sistem pengesanan penipuan sedia ada bergelut dengan analisis masa nyata dan mempunyai keperluan pengiraan yang tinggi, menjadikannya tidak praktikal untuk pelaksanaan yang meluas。",
    "projects.project2.approach": "Memanfaatkan seni bina pembelajaran mendalam untuk mencipta sistem yang ringan dan cekap yang mampu melakukan analisis masa nyata dengan kos pengiraan yang minimum, memberi tumpuan kepada mengoptimumkan kedua-dua ketepatan dan prestasi。",
    "projects.project2.results": "Sistem ini memproses tingkah laku pengguna dalam masa nyata dengan kependaman kurang daripada 200ms, sambil mengekalkan ketepatan pengesanan 95% dan mengurangkan keperluan pengiraan sebanyak 60% berbanding penyelesaian sebelumnya。",
    "projects.project3.title": "Pengesahan Berterusan dengan Biometrik Tingkah Laku",
    "projects.project3.period": "Mei 2024 - Nov 2024",
    "projects.project3.description": "Menjalankan kajian literatur mengenai penggunaan biometrik tingkah laku, khususnya dinamik tetikus dan analisis keystroke, untuk pengesahan pengguna berterusan。",
    "projects.project3.achievement1": "Menyelidik kaedah semasa, cabaran dan penambahbaikan yang berpotensi dalam bidang ini",
    "projects.project3.achievement2": "Mengenal pasti jurang penyelidikan utama dan mencadangkan kaedah pengesahan novel menggunakan keselamatan maklumat biometrik tingkah laku masa nyata (RBBIS)",
    "projects.project3.achievement3": "Membangunkan rangka kerja penyelidikan dan pelan kerja untuk melaksanakan dan menilai kaedah yang dicadangkan",
    "projects.project3.challenge": "Kaedah pengesahan tradisional bergantung pada pengesahan sekali sahaja, mewujudkan kelemahan keselamatan sebaik sahaja pengguna log masuk, manakala kaedah berterusan sering menimbulkan geseran dalam pengalaman pengguna。",
    "projects.project3.approach": "Membangunkan rangka kerja untuk pengesahan pasif dan berterusan yang memantau corak tingkah laku di latar belakang tanpa mengganggu aliran kerja pengguna, menyesuaikan diri dengan perubahan tingkah laku pengguna dari semasa ke semasa。",
    "projects.project3.results": "Rangka kerja yang dicadangkan menunjukkan potensi untuk mengurangkan insiden akses tanpa kebenaran sehingga 87% dalam persekitaran simulasi, sambil mengekalkan pengalaman pengguna yang lancar tanpa gesaan pengesahan tambahan。",
    
    // Services
    "services.title": "Perkhidmatan Saya",
    "services.web": "Pembangunan Aplikasi Web",
    "services.web.desc": "Aplikasi web tersuai yang dibina dengan React dan Next.js, memberi tumpuan kepada prestasi dan pengalaman pengguna。",
    "services.backend": "Pembangunan Backend",
    "services.backend.desc": "Penyelesaian pelayan yang teguh dan boleh skala menggunakan Node.js, Express dan Fastify。",
    "services.api": "Pembangunan API",
    "services.api.desc": "Reka bentuk dan pelaksanaan API RESTful dan GraphQL untuk aliran data yang lancar antara pelanggan dan pelayan。",
    "services.responsive": "Reka Bentuk Responsif",
    "services.responsive.desc": "Reka bentuk web responsif yang mengutamakan mudah alih yang berfungsi dengan sempurna merentas semua peranti dan saiz skrin。",
    
    // Education
    "education.title": "Pendidikan & Pensijilan",
    "education.master": "Sarjana Teknologi Maklumat (Informatik Perniagaan)",
    "education.master.institution": "James Cook University Singapore",
    "education.master.period": "Mac 2024 – Apr 2025",
    "education.master.achievement1": "Mengkhusus dalam analisis data dan risikan perniagaan",
    "education.master.achievement2": "Menjalankan penyelidikan dalam biometrik tingkah laku dan pengesanan penipuan",
    "education.master.achievement3": "Membangunkan model pembelajaran mesin lanjutan untuk aplikasi keselamatan",
    "education.bachelor": "Sarjana Muda Teknologi Maklumat",
    "education.bachelor.institution": "James Cook University Singapore",
    "education.bachelor.period": "Nov 2022 – Feb 2024",
    "education.bachelor.achievement1": "Memberi tumpuan kepada pembangunan perisian dan reka bentuk sistem",
    "education.bachelor.achievement2": "Menyiapkan projek dalam reka bentuk antara muka pengguna dan pembangunan aplikasi",
    "education.bachelor.achievement3": "Memperoleh kepakaran dalam pelbagai bahasa dan rangka kerja pengaturcaraan",
    "education.bachelor.achievement4": "Dianugerahkan pada 7 Mac 2024 dengan GPA 5.27",
    "education.diploma": "Diploma Kebangsaan Tinggi Kejuruteraan Perisian (Tahap 5)",
    "education.diploma.institution": "INET IT ACADEMY",
    "education.diploma.period": "Mac 2018 – Okt 2022",
    "education.diploma.achievement1": "Membangunkan pengetahuan asas dalam prinsip kejuruteraan perisian",
    "education.diploma.achievement2": "Menyiapkan projek praktikal dalam pembangunan aplikasi",
    "education.diploma.achievement3": "Mempelajari metodologi analisis dan reka bentuk sistem",
    "education.achievements": "Pencapaian Utama",
    "education.certifications": "Pensijilan & Testamur",
    "education.verification": "Butiran Pengesahan",
    "education.cert1.title": "Sarjana Muda Teknologi Maklumat",
    "education.cert1.issuer": "James Cook University Singapore",
    "education.cert1.date": "7 Mac 2024",
    "education.cert1.description": "Testamur rasmi untuk ijazah Sarjana Muda Teknologi Maklumat, dianugerahkan pada 7 Mac 2024. Ijazah ini menyediakan asas yang komprehensif dalam konsep teknologi maklumat, pengaturcaraan, reka bentuk pangkalan data dan pembangunan sistem。",
    "education.cert1.verificationMessage": "Butiran pengesahan tidak tersedia untuk testamur ini。",
    "education.cert2.title": "Asas Pemasaran Digital",
    "education.cert2.issuer": "Google Digital Garage",
    "education.cert2.date": "3 April 2023",
    "education.cert2.description": "Pensijilan komprehensif yang merangkumi asas pemasaran digital, termasuk pengoptimuman enjin carian, pemasaran media sosial dan analitik。",
    "education.cert3.title": "Analitis Data Google",
    "education.cert3.issuer": "Google",
    "education.cert3.date": "2023",
    "education.cert3.description": "Pensijilan profesional yang merangkumi analisis data, visualisasi dan tafsiran menggunakan alat analitik Google。",
    "education.verifyAuthenticity": "Sahkan kesahihan sijil ini di:",
    "education.certificateId": "ID Sijil:",
    "education.verificationInfo": "Maklumat Pengesahan",
    "education.verifyButton": "Sahkan Sijil",
    
    // Contact
    "contact.title": "Hubungi Saya",
    "contact.info": "Maklumat Perhubungan",
    "contact.email": "Emel",
    "contact.phone": "Telefon",
    "contact.address": "Alamat",
    "contact.connect": "Berhubung Dengan Saya",
    "contact.connect.desc": "Saya sentiasa terbuka untuk membincangkan projek baharu, idea kreatif atau peluang untuk menjadi sebahagian daripada visi anda。",
    "contact.form.name": "Nama",
    "contact.form.email": "Emel",
    "contact.form.subject": "Subjek",
    "contact.form.message": "Mesej",
    "contact.form.send": "Hantar Mesej",
    "contact.form.sending": "Menghantar...",
    "contact.form.success": "Terima kasih! Mesej anda telah berjaya dihantar. Saya akan menghubungi anda tidak lama lagi。",
    "contact.form.error": "Gagal menghantar borang. Sila cuba lagi。",
    "contact.form.nameRequired": "Nama mesti sekurang-kurangnya 2 aksara",
    "contact.form.emailRequired": "Sila masukkan alamat emel yang sah",
    "contact.form.subjectRequired": "Subjek mesti sekurang-kurangnya 5 aksara",
    "contact.form.messageRequired": "Mesej mesti sekurang-kurangnya 10 aksara",
    
    // Testimonials
    "testimonials.title": "Testimoni Pelanggan",
    "testimonials.prev": "Testimoni sebelumnya",
    "testimonials.next": "Testimoni seterusnya",
    "testimonials.goto": "Pergi ke testimoni {number}",
    "testimonials.client1.quote": "Kepakaran Kaung dalam membangunkan sistem POS kami telah mengubah operasi perniagaan kami. Perhatiannya terhadap perincian dan kemahiran menyelesaikan masalah adalah luar biasa。",
    "testimonials.client1.name": "Sarah Chen",
    "testimonials.client1.title": "Pengurus Operasi, RetailTech Solutions",
    "testimonials.client2.quote": "Bekerja dengan Kaung pada sistem pengesanan penipuan kami adalah satu perubahan besar. Pemahamannya yang mendalam tentang biometrik tingkah laku dan pembelajaran mesin memberikan hasil yang melebihi jangkaan kami。",
    "testimonials.client2.name": "Michael Rodriguez",
    "testimonials.client2.title": "CTO, SecureFinance",
    "testimonials.client3.quote": "Keupayaan Kaung untuk menterjemahkan keperluan teknikal yang kompleks kepada penyelesaian mesra pengguna adalah luar biasa. Kerjanya pada infrastruktur rangkaian kami telah meningkatkan kestabilan sistem kami dengan ketara。",
    "testimonials.client3.name": "Priya Sharma",
    "testimonials.client3.title": "Pengarah IT, Global Connect",

    // System Monitor
    "systemMonitor.title": "Monitor Sistem",
    "systemMonitor.systemTime": "Masa Sistem",
    "systemMonitor.cpuUsage": "Penggunaan CPU",
    "systemMonitor.memoryUsage": "Penggunaan Memori",
    "systemMonitor.networkActivity": "Aktiviti Rangkaian",
    "systemMonitor.skillsMonitor": "Monitor Kemahiran",
    "systemMonitor.show": "Tunjukkan Antara Muka",
    "systemMonitor.hide": "Sembunyikan Antara Muka",

    // Terminal
    "terminal.title": "KSL DevConsole",
    "terminal.welcome": "Selamat datang ke portfolio Kaung Sithu Linn. Taip 'help' untuk melihat arahan yang tersedia。",
    "terminal.help": "Arahan yang tersedia",
    "terminal.about": "Tentang",
    "terminal.skills": "Kemahiran",
    "terminal.projects": "Projek",
    "terminal.contact": "Hubungi",
    "terminal.experience": "Pengalaman",
    "terminal.education": "Pendidikan",
    "terminal.clear": "Kosongkan terminal",
    "terminal.exit": "Keluar dari mod terminal",
    "terminal.askAI": "Tanya pembantu AI",

    // File Explorer
    "fileExplorer.title": "Penjelajah Portfolio",
    "fileExplorer.projects": "Projek",
    "fileExplorer.resume": "Resume",
    "fileExplorer.certificates": "Sijil",
    "fileExplorer.mainPython": "Skrip Python utama untuk sistem pengesanan penipuan",
    "fileExplorer.model": "Model pembelajaran mesin terlatih",
    "fileExplorer.readme": "Dokumentasi projek",
    "fileExplorer.authSystem": "Pelaksanaan sistem pengesahan",
    "fileExplorer.researchPaper": "Kertas penyelidikan mengenai biometrik tingkah laku",
    "fileExplorer.currentResume": "Resume profesional semasa",
    "fileExplorer.profilePhoto": "Gambar profil profesional",
    "fileExplorer.bachelorCert": "Sijil ijazah Sarjana Muda Teknologi Maklumat",
    "fileExplorer.googleCert": "Pensijilan Pemasaran Digital Google",
  },
  ta: {
    // Common
    "common.language": "மொழி",
    "common.english": "English",
    "common.chinese": "中文",
    "common.malay": "Bahasa Melayu",
    "common.tamil": "தமிழ்",
    "common.arabic": "العربية",
    "common.learnMore": "மேலும் அறிக",
    "common.contactMe": "என்னை தொடர்பு கொள்ளவும்",
    "common.downloadResume": "சுயவிவரத்தை பதிவிறக்குக",
    "common.resume": "சுயவிவரம்",
    "common.scrollTo": "{section}க்கு ஸ்க்ரோல் செய்யவும்",
    "common.loading": "ஏற்றுகிறது...",
    "common.close": "மூடு",
    "common.open": "திற",
    "common.view": "காண்க",
    "common.hide": "மறை",
    "common.show": "காட்டு",
    "common.back": "மீண்டும்",
    "common.next": "அடுத்தது",
    "common.previous": "முந்தையது",
    "common.submit": "சமர்ப்பிக்கவும்",
    "common.cancel": "ரத்து செய்",
    "common.save": "சேமிக்கவும்",
    "common.delete": "அழி",
    "common.edit": "தொகு",
    "common.search": "தேடு",
    "common.filter": "வடிகட்டி",
    "common.sort": "வகைபடுத்து",
    "common.all": "அனைத்தும்",
    "common.none": "யாரும் இல்லை",
    "common.yes": "ஆம்",
    "common.no": "இல்லை",
    "common.success": "வெற்றி",
    "common.error": "பிழை",
    "common.warning": "எச்சரிக்கை",
    "common.info": "தகவல்",

    // Navigation
    "nav.home": "முகப்பு",
    "nav.about": "பற்றி",
    "nav.experience": "அனுபவம்",
    "nav.skills": "திறன்கள்",
    "nav.projects": "திட்டங்கள்",
    "nav.services": "சேவைகள்",
    "nav.testimonials": "சான்றுகள்",
    "nav.education": "கல்வி",
    "nav.contact": "தொடர்பு",
    "nav.scrollTo": "{section}க்கு ஸ்க்ரோல் செய்யவும்",

    // Hero
    "hero.tagline": "டிஜிட்டல் தீர்வுகளை உருவாக்குதல்",
    "hero.title": "Kaung Sithu Linn",
    "hero.subtitle": "மென்பொருள் டெவலப்பர்",
    "hero.jobTitle": "மென்பொருள் டெவலப்பர்",
    "hero.description": "4+ ஆண்டுகள் அனுபவம் கொண்ட டெவலப்பர், நேர்த்தியான பயனர் இடைமுகங்களை உருவாக்குதல், முழுமையான சோதனை நடத்துதல் மற்றும் சிக்கலான தேவைகளை பூர்த்தி செய்யும் உயர் தரமான பயன்பாடுகளை வழங்குதல். POS அமைப்புகள், மோசடி கண்டறிதல் மற்றும் நடத்தை பயோமெட்ரிக்ஸ் ஆகியவற்றில் நிபுணத்துவம்.",
    "hero.githubProfile": "GitHub சுயவிவரம்",
    "hero.linkedinProfile": "LinkedIn சுயவிவரம்",
    "hero.emailContact": "மின்னஞ்சல் தொடர்பு",
    "hero.portfolioWebsite": "போர்ட்ஃபோலியோ வலைத்தளம்",
    "hero.downloadResume": "சுயவிவரத்தை பதிவிறக்குக",
    "hero.resume": "சுயவிவரம்",
    "hero.learnMore": "மேலும் அறிக",
    "hero.contactMe": "என்னை தொடர்பு கொள்ளவும்",
    "hero.profileImageAlt": "Kaung Sithu Linn - மென்பொருள் டெவலப்பர்",

    // About
    "about.title": "என்னை பற்றி",
    "about.paragraph1": "சிங்கப்பூரை மையமாகக் கொண்டு செயல்படும் ஒரு ஆர்வமுள்ள மென்பொருள் டெவலப்பராக, பயனர் அனுபவம் மற்றும் அமைப்பு மேம்பாட்டில் கவனம் செலுத்தி வலுவான பயன்பாடுகளை உருவாக்குவதில் நிபுணத்துவம் பெற்றுள்ளேன். eVolva Software House இல் 4 ஆண்டுகளுக்கும் மேலாக, புதுமையான POS அமைப்புகள் மற்றும் நெட்வொர்க் தீர்வுகள் மூலம் வணிக செயல்பாடுகளை மாற்றியமைத்துள்ளேன்.",
    "about.paragraph2": "எனது சமீபத்திய ஆராய்ச்சி, இயந்திரக் கற்றலின் மூலம் நடத்தை பயோமெட்ரிக்ஸ் மற்றும் மோசடி கண்டறிதலில் கவனம் செலுத்துகிறது. டிஜிட்டல் மார்க்கெட்டிங் அடிப்படைகளில் சான்றிதழ் பெற்றுள்ளேன், இது எனக்கு தொழில்நுட்ப மேம்பாட்டை பயனுள்ள சந்தை உத்திகளுடன் இணைக்க அனுமதிக்கிறது. தற்போது, நான் ஜேம்ஸ் குக் பல்கலைக்கழகம் சிங்கப்பூரில் தகவல் தொழில்நுட்பத்தில் என் மாஸ்டர்ஸ் படிப்பைத் தொடர்கிறேன், அங்கு தரவுப் பகுப்பாய்வு மற்றும் AI பயன்பாடுகளில் எனது நிபுணத்துவத்தை விரிவுபடுத்தி வருகிறேன்.",
    "about.quote": "சிக்கல்களைத் தீர்க்கும்だけでなく, மனித அனுபவங்களை மேம்படுத்தும் தொழில்நுட்பத்தை உருவாக்குவதில் நம்புகிறேன். உண்மையான மாற்றத்தை ஏற்படுத்தும் பாதுகாப்பான, திறமையான மற்றும் பயனர் நட்பு தீர்வுகளை உருவாக்குவதே எனது நோக்கம்.",
    "about.decorativeImageAlt": "அலங்கார பின்னணி",
    "about.skills.frontend.title": "முன்னணி",
    "about.skills.frontend.description": "JavaScript, HTML5, CSS, UI வடிவமைப்பு",
    "about.skills.backend.title": "பின்புறம்",
    "about.skills.backend.description": "Python, Java, C++, .NET",
    "about.skills.database.title": "தரவுத்தொகுப்பு",
    "about.skills.database.description": "SQL, தரவுப் மேலாண்மை",
    "about.skills.ai.title": "AI/ML",
    "about.skills.ai.description": "நடத்தை பயோமெட்ரிக்ஸ், ஆழமான கற்றல்",
    "about.skills.marketing.title": "டிஜிட்டல் மார்க்கெட்டிங்",
    "about.skills.marketing.description": "SEO, பகுப்பாய்வு, உள்ளடக்க உத்தி",
    "about.skills.languages.title": "மொழிகள்",
    "about.skills.languages.description": "ஆங்கிலம், பர்மீஸ், சீனம், ஜப்பானியம்",
    
    // Header
    "header.about": "பற்றி",
    "header.experience": "அனுபவம்",
    "header.skills": "திறன்கள்",
    "header.services": "சேவைகள்",
    "header.education": "கல்வி",
    "header.contact": "தொடர்பு",
    
    // Skills
    "skills.title": "திறன்கள் & நிபுணத்துவம்",
    "skills.frontend": "முன்னணி மேம்பாடு",
    "skills.frontend.tech": "JavaScript, HTML5, CSS",
    "skills.frontend.desc": "நவீன வலை தொழில்நுட்பங்களுடன் பதிலளிக்கும் மற்றும் இடைமுக பயனர் இடைமுகங்களை உருவாக்குதல்.",
    "skills.backend": "பின்புற மேம்பாடு",
    "skills.backend.tech": "Python, Java, C++, .NET",
    "skills.backend.desc": "செயல்திறன் மற்றும் நம்பகத்தன்மையில் கவனம் செலுத்தி வலுவான சர்வர் பக்க பயன்பாடுகளை உருவாக்குதல்.",
    "skills.database": "தரவுத்தொகுப்பு மேலாண்மை",
    "skills.database.tech": "SQL, தரவுப் மேலாண்மை",
    "skills.database.desc": "சிறந்த தரவுப் மேலாண்மைக்காக திறமையான தரவுத்தொகுப்பு திட்டங்கள் மற்றும் கேள்விகளை வடிவமைத்தல் மற்றும் செயல்படுத்துதல்.",
    "skills.uiux": "UI/UX வடிவமைப்பு",
    "skills.uiux.tech": "பயனர் இடைமுக வடிவமைப்பு",
    "skills.uiux.desc": "பயன்பாட்டில் மற்றும் அணுகல் திறனில் கவனம் செலுத்தி நேர்த்தியான பயனர் இடைமுகங்களை உருவாக்குதல்.",
    "skills.ml": "இயந்திரக் கற்றல்",
    "skills.ml.tech": "நடத்தை பயோமெட்ரிக்ஸ், ஆழமான கற்றல்",
    "skills.ml.desc": "நடத்தை முறைபாடுகளைப் பயன்படுத்தி மோசடி கண்டறிதல் மற்றும் பயனர் அங்கீகாரத்திற்கான ML மாதிரிகளை உருவாக்குதல்.",
    "skills.programming": "நிரலாக்க மொழிகள்",
    "skills.programming.tech": "JavaScript, Python, Java, C++",
    "skills.programming.desc": "பல்வேறு பயன்பாடுகளுக்காக பல நிரலாக்க மொழிகளில் திறமையான குறியீடுகளை எழுதுதல்.",
    "skills.multilingual": "பல மொழிகள்",
    "skills.multilingual.tech": "ஆங்கிலம், பர்மீஸ், சீனம், ஜப்பானியம்",
    "skills.multilingual.desc": "சர்வதேச ஒத்துழைப்பிற்காக பல மொழிகளில் திறமையாக தொடர்பு கொள்ளுதல்.",
    "skills.communication": "தொடர்பு",
    "skills.communication.tech": "தொழில்நுட்ப எழுத்து, பொது பேச்சு",
    "skills.communication.desc": "தொழில்நுட்ப மற்றும் தொழில்நுட்பமற்ற பார்வையாளர்களுக்கு சிக்கலான தொழில்நுட்பக் கருத்துக்களை தெளிவாகக் கூறுதல்.",
    "skills.optimization": "அமைப்பு மேம்பாடு",
    "skills.optimization.tech": "செயல்திறன் டியூனிங், நெட்வொர்க் தீர்வுகள்",
    "skills.optimization.desc": "சிறந்த செயல்பாட்டிற்காக அமைப்பு செயல்திறனை மேம்படுத்துதல் மற்றும் சிக்கலான தொழில்நுட்ப சிக்கல்களைத் தீர்க்குதல்.",
    "skills.research": "ஆராய்ச்சி",
    "skills.research.tech": "கல்வி ஆராய்ச்சி, இலக்கிய விமர்சனம்",
    "skills.research.desc": "தொழில்நுட்பத்தில் இடைவெளிகளை அடையாளம் காண மற்றும் புதுமையான தீர்வுகளை முன்மொழிய விரிவான ஆராய்ச்சியை நடத்துதல்。",

    // Experience
    "experience.title": "தொழில்முறை அனுபவம்",
    "experience.company": "eVolva Software House",
    "experience.location": "மண்டலே, மியான்மர்",
    "experience.period": "டிச 2018 - தற்போது",
    "experience.role": "மென்பொருள் டெவலப்பர் மற்றும் கிளையண்ட் டெஸ்டர்",
    "experience.responsibilities.1": "செயல்திறனை மேம்படுத்துவதற்காக பங்கு மற்றும் சரக்கு மேலாண்மையைச் சரிசெய்ய Microsoft .NET ஐப் பயன்படுத்தி POS அமைப்பை வடிவமைத்து உருவாக்கியது",
    "experience.responsibilities.2": "செயல்திறனை மேம்படுத்துவதற்காக பழைய Microsoft Access (Office 2003) POS அமைப்பை நவீன SQL தனித்துவமான பயன்பாட்டாக மேம்படுத்தியது",
    "experience.responsibilities.3": "தனிப்பயன் சுரங்கத் தீர்வைச் செயல்படுத்துவதன் மூலம் VPN நெட்வொர்க்குடன் LAN இடையூறு சிக்கல்களைத் தீர்த்து, நிலையான இணைப்பை உறுதிசெய்தது",
    "experience.responsibilities.4": "பரிவர்த்தனை நேரத்தை குறைத்து சரக்கு கண்காணிப்பை மேம்படுத்தி, கடை செயல்திறனை 50% மேம்படுத்திய ஒரு மேம்படுத்தப்பட்ட POS அமைப்பை வழங்கியது",
    "experience.responsibilities.5": "புதிய அமைப்புகளைச் சரளமாக ஏற்றுக்கொள்வதற்காக விரிவான சோதனை மற்றும் கிளையண்ட் பயிற்சியை நடத்தியது",
    "experience.decorativeImageAlt": "அலங்கார பின்னணி",
    "experience.keyAchievements": "முக்கிய சாதனைகள்",
    
    // Projects
    "projects.title": "சிறந்த திட்டங்கள்",
    "projects.viewProject": "திட்டத்தைப் பார்க்கவும்",
    "projects.hideCase": "வழக்கு ஆய்வை மறைக்கவும்",
    "projects.viewCase": "வழக்கு ஆய்வைப் பார்க்கவும்",
    "projects.challenge": "சவால்",
    "projects.approach": "நெருங்குதல்",
    "projects.results": "முடிவுகள்",
    "projects.technologies": "பயன்படுத்திய தொழில்நுட்பங்கள்",
    "projects.project1.title": "ஆன்லைன் மதிப்பீட்டிற்கான மோசடி கண்டறிதலுக்கான மவுஸ் டைனமிக்ஸ்",
    "projects.project1.period": "மே 2024 - நவம்பர் 2024",
    "projects.project1.description": "நடத்தை பயோமெட்ரிக் ஆக மவுஸ் டைனமிக்ஸைப் பயன்படுத்தி ஆன்லைன் மதிப்பீட்டுகளின் போது மோசடி நடத்தும் நடத்தை கண்டறிய இயந்திரக் கற்றல் மாதிரியை உருவாக்கியது.",
    "projects.project1.achievement1": "பயனர் சுயவிவரங்களை உருவாக்க மற்றும் மோசடியை குறிக்கக்கூடிய அசாதாரணங்களை அடையாளம் காண மவுஸ் இயக்கம் மற்றும் கிளிக் முறைபாடுகளைப் பகுப்பாய்வு செய்தது",
    "projects.project1.achievement2": "சிறந்த செயல்திறனைப் பெறும் தொழில்நுட்பங்களைச் செயல்படுத்தி, பல இயந்திரக் கற்றல் மாதிரிகளை மதிப்பீடு செய்து, மோசடி கண்டறிதலில் உயர் துல்லியத்தை அடைந்தது",
    "projects.project1.achievement3": "பயனர் அங்கீகாரத்திற்காக மிகவும் வேறுபட்ட முக்கிய மவுஸ் டைனமிக்ஸ் அம்சங்களை அடையாளம் கண்டது",
    "projects.project1.challenge": "சிக்கலான மோசடி நுட்பங்களை கண்டறிய பாரம்பரிய ப்ராக்டரிங் முறைகள் போதுமானதாக இல்லை என்பதால் கல்வி நிறுவனங்கள் ஆன்லைன் மதிப்பீட்டுகளில் மோசடி சம்பவங்கள் அதிகரித்தன.",
    "projects.project1.approach": "பயனர் தனியுரிமையை பாதிக்காமல் அல்லது கூடுதல் ஹார்ட்வேரைத் தேவையில்லாமல் அசாதாரண நடத்தை அடையாளம் காண மவுஸ் இயக்க முறைபாடுகளைப் பகுப்பாய்வு செய்யும் ஒரு மையமற்ற நடத்தை பயோமெட்ரிக் அமைப்பை உருவாக்கியது.",
    "projects.project1.results": "மோசடி நடத்தும் நடத்தை கண்டறிய 92% துல்லியத்தை அடைந்தது, 3% மட்டுமே தவறான நேர்மறை விகிதத்தைப் பெற்றது, மதிப்பீட்டு நேர்மையை முக்கியமாக மேம்படுத்தியது, அதே நேரத்தில் நேர்மறையான பயனர் அனுபவத்தைப் பராமரித்தது.",
    "projects.project2.title": "ஆழமான கற்றலைப் பயன்படுத்தி மவுஸ் டைனமிக்ஸ் பயோமெட்ரிக் மோசடி கண்டறிதல் அமைப்பு",
    "projects.project2.period": "மே 2024 - நவம்பர் 2024",
    "projects.project2.description": "ஆன்லைன் மதிப்பீட்டுகளின் பாதுகாப்பை மேம்படுத்த மவுஸ் டைனமிக்ஸ் மற்றும் ஆழமான கற்றலைப் பயன்படுத்தி மோசடி கண்டறிதல் அமைப்பை உருவாக்கியது.",
    "projects.project2.achievement1": "100% தரவுப் பயன்பாட்டை அடையும் தரவுப் ப்ராப்ராசசிங் குழாய்களைச் செயல்படுத்தியது",
    "projects.project2.achievement2": "மேம்பட்ட தேர்வு முறைகளைப் பயன்படுத்தி 12 சிறந்த அம்சத் தொகுப்புகளை வடிவமைத்தது",
    "projects.project2.achievement3": "பல ஆழமான கற்றல் மாதிரிகளை (ANN, LSTM, LSTM-CNN, LSTM-Transformer) உருவாக்கி சோதித்தது",
    "projects.project2.achievement4": "அமைப்பு செயல்திறனை கண்காணிக்க தரவுப் காட்சிப்படுத்தல் கருவிகளை உருவாக்கியது",
    "projects.project2.achievement5": "திட்ட இலக்குகளை மீறி, 95% கண்டறிதல் துல்லியத்தை அடைந்து, 5% க்குக் குறைவான தவறான எதிர்மறை விகிதத்தை அடைந்தது",
    "projects.project2.challenge": "உண்மையான நேரப் பகுப்பாய்வுடன் போராடிய மற்றும் உயர் கணக்கீட்டு தேவைகளை கொண்டிருந்த தற்போதைய மோசடி கண்டறிதல் அமைப்புகள், பரந்த அளவில் செயல்படுத்துவதற்கு அவை நடைமுறைக்கு ஒவ்வாதவையாக இருந்தன.",
    "projects.project2.approach": "இரண்டு துல்லியத்தையும் செயல்திறனையும் மேம்படுத்துவதில் கவனம் செலுத்தி, குறைந்த கணக்கீட்டு மேலதிக செலவுடன் நேரடி பகுப்பாய்வைச் செய்யக்கூடிய இலகுரக, திறமையான அமைப்பை உருவாக்க ஆழமான கற்றல் கட்டமைப்புகளைப் பயன்படுத்தியது.",
    "projects.project2.results": "முந்தைய தீர்வுகளுடன் ஒப்பிடும்போது கணக்கீட்டு தேவைகளை 60% குறைத்து, 200ms க்கும் குறைவான தாமதத்துடன் நேரடியாக பயனர் நடத்தை செயலாக்கியது, அதே நேரத்தில் 95% கண்டறிதல் துல்லியத்தைப் பராமரித்தது.",
    "projects.project3.title": "நடத்தை பயோமெட்ரிக்ஸுடன் தொடர்ச்சியான அங்கீகாரம்",
    "projects.project3.period": "மே 2024 - நவம்பர் 2024",
    "projects.project3.description": "தொடர்ச்சியான பயனர் அங்கீகாரத்திற்காக நடத்தை பயோமெட்ரிக்ஸ், குறிப்பாக மவுஸ் டைனமிக்ஸ் மற்றும் கீஸ்ட்ரோக் பகுப்பாய்வைப் பயன்படுத்தும் இலக்கிய விமர்சனம் நடத்தப்பட்டது.",
    "projects.project3.achievement1": "இந்த துறையில் தற்போதைய முறைகள், சவால்கள் மற்றும் சாத்தியமான மேம்பாடுகளை ஆராய்ந்தது",
    "projects.project3.achievement2": "முக்கிய ஆராய்ச்சி இடைவெளிகளை அடையாளம் கண்டு, நேரடி நடத்தை பயோமெட்ரிக் தகவல் பாதுகாப்பைப் (RBBIS) பயன்படுத்தி ஒரு புதுமையான அங்கீகார முறையை முன்மொழிந்தது",
    "projects.project3.achievement3": "முன்மொழியப்பட்ட முறையை செயல்படுத்தி மதிப்பீடு செய்ய ஆராய்ச்சி கட்டமைப்பு மற்றும் வேலைத் திட்டத்தை உருவாக்கியது",
    "projects.project3.challenge": "பாரம்பரிய அங்கீகார முறைகள் ஒரே நேரத்தில் சரிபார்ப்பில் நம்பிக்கை வைக்கின்றன, பயனர் உள்நுழைந்த பிறகு பாதுகாப்பு பாதிப்புகளை உருவாக்குகின்றன, ஆனால் தொடர்ச்சியான முறைகள் பெரும்பாலும் பயனர் அனுபவத்தில் உராய்வை உருவாக்குகின்றன.",
    "projects.project3.approach": "பயனர் பணியினைத் தடை செய்யாமல் பின்னணியில் நடத்தை முறைபாடுகளை கண்காணிக்கும் பாசிசமான, தொடர்ச்சியான அங்கீகாரத்திற்கான ஒரு கட்டமைப்பை உருவாக்கியது, காலப்போக்கில் மாறும் பயனர் நடத்தைக்கு ஏற்ப மாறுகிறது.",
    "projects.project3.results": "முன்மொழியப்பட்ட கட்டமைப்பு, கூடுதல் அங்கீகார உந்துதல்களின்றி ஒரு சரளமான பயனர் அனுபவத்தை பராமரிக்கும்போது, சிமுலேட்டட் சூழல்களில் அனுமதியற்ற அணுகல் சம்பவங்களை 87% வரை குறைக்கும் திறனை வெளிப்படுத்தியது.",
    
    // Services
    "services.title": "எனது சேவைகள்",
    "services.web": "வலை பயன்பாட்டு மேம்பாடு",
    "services.web.desc": "செயல்திறன் மற்றும் பயனர் அனுபவத்தில் கவனம் செலுத்தி React மற்றும் Next.js உடன் கட்டப்பட்ட தனிப்பயன் வலை பயன்பாடுகள்.",
    "services.backend": "பின்புற மேம்பாடு",
    "services.backend.desc": "Node.js, Express மற்றும் Fastify ஐப் பயன்படுத்தி வலுவான மற்றும் அளவிடக்கூடிய சர்வர் பக்க தீர்வுகள்.",
    "services.api": "API மேம்பாடு",
    "services.api.desc": "வாடிக்கையாளர் மற்றும் சர்வர் இடையே தரவின் சரளமான ஓட்டத்திற்கான RESTful மற்றும் GraphQL API வடிவமைப்பு மற்றும் செயல்பாடு.",
    "services.responsive": "பதிலளிக்கும் வடிவமைப்பு",
    "services.responsive.desc": "அனைத்து சாதனங்கள் மற்றும் திரை அளவுகளிலும் குறைபாடின்றி செயல்படும் மொபைல்-முதலில், பதிலளிக்கும் வலை வடிவமைப்புகள்.",
    
    // Education
    "education.title": "கல்வி & சான்றிதழ்கள்",
    "education.master": "மாஸ்டர் ஆஃப் இன்ஃபர்மேஷன் டெக்னாலஜி (பிசினஸ் இன்ஃபர்மாடிக்ஸ்)",
    "education.master.institution": "ஜேம்ஸ் குக் பல்கலைக்கழகம் சிங்கப்பூர்",
    "education.master.period": "மார்ச் 2024 – ஏப் 2025",
    "education.master.achievement1": "தரவுப் பகுப்பாய்வு மற்றும் வணிக நுண்ணறிவில் நிபுணத்துவம்",
    "education.master.achievement2": "நடத்தை பயோமெட்ரிக்ஸ் மற்றும் மோசடி கண்டறிதலில் ஆராய்ச்சி நடத்துதல்",
    "education.master.achievement3": "பாதுகாப்பு பயன்பாடுகளுக்கான மேம்பட்ட இயந்திரக் கற்றல் மாதிரிகளை உருவாக்குதல்",
    "education.bachelor": "பிஎஸ்சி தகவல் தொழில்நுட்பம்",
    "education.bachelor.institution": "ஜேம்ஸ் குக் பல்கலைக்கழகம் சிங்கப்பூர்",
    "education.bachelor.period": "நவம்பர் 2022 – பிப் 2024",
    "education.bachelor.achievement1": "மென்பொருள் மேம்பாடு மற்றும் அமைப்பு வடிவமைப்பில் கவனம் செலுத்துதல்",
    "education.bachelor.achievement2": "பயனர் இடைமுக வடிவமைப்பு மற்றும் பயன்பாட்டு மேம்பாட்டில் திட்டங்களை முடித்தது",
    "education.bachelor.achievement3": "பல நிரலாக்க மொழிகள் மற்றும் கட்டமைப்புகளில் நிபுணத்துவத்தைப் பெற்றது",
    "education.bachelor.achievement4": "7 மார்ச் 2024 அன்று GPA 5.27 உடன் வழங்கப்பட்டது",
    "education.diploma": "மென்பொருள் பொறியியல் உயர் தேசிய டிப்ளோமா (நிலை 5)",
    "education.diploma.institution": "INET IT ACADEMY",
    "education.diploma.period": "மார்ச் 2018 – அக்டோபர் 2022",
    "education.diploma.achievement1": "மென்பொருள் பொறியியல் கொள்கைகளில் அடிப்படை அறிவை உருவாக்கியது",
    "education.diploma.achievement2": "பயன்பாட்டு மேம்பாட்டில் நடைமுறை திட்டங்களை முடித்தது",
    "education.diploma.achievement3": "அமைப்பு பகுப்பாய்வு மற்றும் வடிவமைப்பு முறைமைகளை கற்றது",
    "education.achievements": "முக்கிய சாதனைகள்",
    "education.certifications": "சான்றிதழ்கள் & டெஸ்டமர்ஸ்",
    "education.verification": "சரிபார்ப்பு விவரங்கள்",
    "education.cert1.title": "பிஎஸ்சி தகவல் தொழில்நுட்பம்",
    "education.cert1.issuer": "ஜேம்ஸ் குக் பல்கலைக்கழகம் சிங்கப்பூர்",
    "education.cert1.date": "மார்ச் 7, 2024",
    "education.cert1.description": "பிஎஸ்சி தகவல் தொழில்நுட்பம் பட்டத்திற்கு அதிகாரப்பூர்வமான சான்றிதழ், மார்ச் 7, 2024 அன்று வழங்கப்பட்டது. இந்த பட்டம் தகவல் தொழில்நுட்பக் கருத்துக்கள், நிரலாக்கம், தரவுத்தொகுப்பு வடிவமைப்பு மற்றும் அமைப்பு மேம்பாட்டில் விரிவான அடிப்படை அறிவை வழங்குகிறது.",
    "education.cert1.verificationMessage": "இந்த சான்றிதழுக்கு சரிபார்ப்பு விவரங்கள் கிடைக்கவில்லை.",
    "education.cert2.title": "டிஜிட்டல் மார்க்கெட்டிங்கின் அடிப்படைகள்",
    "education.cert2.issuer": "Google Digital Garage",
    "education.cert2.date": "ஏப்ரல் 3, 2023",
    "education.cert2.description": "டிஜிட்டல் மார்க்கெட்டிங் அடிப்படைகளை உள்ளடக்கிய விரிவான சான்றிதழ், இதில் தேடல் இயந்திரம் ஆப்டிமைசேஷன், சமூக ஊடக மார்க்கெட்டிங் மற்றும் பகுப்பாய்வு ஆகியவை அடங்கும்.",
    "education.cert3.title": "Google தரவுப் பகுப்பாய்வு",
    "education.cert3.issuer": "Google",
    "education.cert3.date": "2023",
    "education.cert3.description": "Google இன் பகுப்பாய்வு கருவிகளைப் பயன்படுத்தி தரவுப் பகுப்பாய்வு, காட்சிப்படுத்தல் மற்றும் விளக்கம் ஆகியவற்றை உள்ளடக்கிய தொழில்முறை சான்றிதழ்.",
    "education.verifyAuthenticity": "இந்த சான்றிதழின் உண்மைத்தன்மையை சரிபார்க்கவும்:",
    "education.certificateId": "சான்றிதழ் ஐடி:",
    "education.verificationInfo": "சரிபார்ப்பு தகவல்",
    "education.verifyButton": "சான்றிதழை சரிபார்க்கவும்",
    
    // Contact
    "contact.title": "என்னை தொடர்பு கொள்ளவும்",
    "contact.info": "தொடர்பு தகவல்",
    "contact.email": "மின்னஞ்சல்",
    "contact.phone": "தொலைபேசி",
    "contact.address": "முகவரி",
    "contact.connect": "என்னுடன் இணைக்கவும்",
    "contact.connect.desc": "புதிய திட்டங்கள், படைப்பாற்றல் யோசனைகள் அல்லது உங்கள் பார்வையின் ஒரு பகுதியாகும் வாய்ப்புகளைப் பற்றி விவாதிக்க நான் எப்போதும் திறந்தவனாக இருக்கிறேன்.",
    "contact.form.name": "பெயர்",
    "contact.form.email": "மின்னஞ்சல்",
    "contact.form.subject": "பொருள்",
    "contact.form.message": "செய்தி",
    "contact.form.send": "செய்தியை அனுப்பவும்",
    "contact.form.sending": "அனுப்புகிறது...",
    "contact.form.success": "நன்றி! உங்கள் செய்தி வெற்றிகரமாக அனுப்பப்பட்டது. நான் விரைவில் உங்களைத் தொடர்புகொள்வேன்.",
    "contact.form.error": "படிவத்தைச் சமர்ப்பிக்கத் தவறிவிட்டது. மீண்டும் முயற்சிக்கவும்.",
    "contact.form.nameRequired": "பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்",
    "contact.form.emailRequired": "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்",
    "contact.form.subjectRequired": "பொருள் குறைந்தது 5 எழுத்துகள் இருக்க வேண்டும்",
    "contact.form.messageRequired": "செய்தி குறைந்தது 10 எழுத்துகள் இருக்க வேண்டும்",
    
    // Testimonials
    "testimonials.title": "வாடிக்கையாளர் சான்றுகள்",
    "testimonials.prev": "முந்தைய சான்று",
    "testimonials.next": "அடுத்த சான்று",
    "testimonials.goto": "சான்றுக்கு செல்லவும் {number}",
    "testimonials.client1.quote": "எங்கள் POS அமைப்பை உருவாக்குவதில் காங் நிபுணத்துவம் எங்கள் வணிக செயல்பாடுகளை மாற்றியது. விவரங்களுக்கு அவரது கவனம் மற்றும் சிக்கல் தீர்க்கும் திறன்கள் சிறப்பானவை.",
    "testimonials.client1.name": "சாரா சென்",
    "testimonials.client1.title": "ஆபரேஷன்ஸ் மேனேஜர், ரீடெயில் டெக் சால்யூஷன்ஸ்",
    "testimonials.client2.quote": "எங்கள் மோசடி கண்டறிதல் அமைப்பில் காங் உடன் வேலை செய்வது ஒரு விளையாட்டு மாற்றியாக இருந்தது. நடத்தை பயோமெட்ரிக்ஸ் மற்றும் இயந்திரக் கற்றலின் மீது அவரது ஆழமான புரிதல் எங்கள் எதிர்பார்ப்புகளை மீறிய முடிவுகளை வழங்கியது.",
    "testimonials.client2.name": "மைக்கேல் ரொட்ரிகஸ்",
    "testimonials.client2.title": "CTO, SecureFinance",
    "testimonials.client3.quote": "சிக்கலான தொழில்நுட்ப தேவைகளை பயனர் நட்பு தீர்வுகளாக மாற்ற காங் திறன் குறிப்பிடத்தக்கது. எங்கள் நெட்வொர்க் உள்கட்டமைப்பில் அவரது வேலை எங்கள் அமைப்பு நிலைத்தன்மையை முக்கியமாக மேம்படுத்தியது.",
    "testimonials.client3.name": "பிரியா சர்மா",
    "testimonials.client3.title": "ஐடி இயக்குனர், குளோபல் கனெக்ட்",

    // System Monitor
    "systemMonitor.title": "அமைப்பு கண்காணிப்பு",
    "systemMonitor.systemTime": "அமைப்பு நேரம்",
    "systemMonitor.cpuUsage": "CPU பயன்பாடு",
    "systemMonitor.memoryUsage": "நினைவக பயன்பாடு",
    "systemMonitor.networkActivity": "நெட்வொர்க் செயல்பாடு",
    "systemMonitor.skillsMonitor": "திறன்கள் கண்காணிப்பு",
    "systemMonitor.show": "இடைமுகத்தை காட்டு",
    "systemMonitor.hide": "இடைமுகத்தை மறை",

    // Terminal
    "terminal.title": "KSL DevConsole",
    "terminal.welcome": "Kaung Sithu Linn இன் போர்ட்ஃபோலியோவுக்கு வரவேற்கிறோம். கிடைக்கக்கூடிய கட்டளைகளைப் பார்க்க 'உதவி' எனத் தட்டச்சு செய்யவும்.",
    "terminal.help": "கிடைக்கக்கூடிய கட்டளைகள்",
    "terminal.about": "பற்றி",
    "terminal.skills": "திறன்கள்",
    "terminal.projects": "திட்டங்கள்",
    "terminal.contact": "தொடர்பு",
    "terminal.experience": "அனுபவம்",
    "terminal.education": "கல்வி",
    "terminal.clear": "முனையத்தை அழிக்கவும்",
    "terminal.exit": "முனை முறைமையிலிருந்து வெளியேறவும்",
    "terminal.askAI": "AI உதவியாளரை  கேளுங்கள்",

    // File Explorer
    "fileExplorer.title": "போர்ட்ஃபோலியோ எக்ஸ்ப்ளோரர்",
    "fileExplorer.projects": "திட்டங்கள்",
    "fileExplorer.resume": "சுயவிவரம்",
    "fileExplorer.certificates": "சான்றிதழ்கள்",
    "fileExplorer.mainPython": "மோசடி கண்டறிதல் அமைப்பிற்கான முக்கிய Python ஸ்கிரிப்ட்",
    "fileExplorer.model": "பயிற்சி பெற்ற இயந்திரக் கற்றல் மாதிரி",
    "fileExplorer.readme": "திட்ட ஆவணங்கள்",
    "fileExplorer.authSystem": "அங்கீகார அமைப்பு செயலாக்கம்",
    "fileExplorer.researchPaper": "நடத்தை பயோமெட்ரிக்ஸ் குறித்த ஆராய்ச்சி கட்டுரை",
    "fileExplorer.currentResume": "தற்போதைய தொழில்முறை சுயவிவரம்",
    "fileExplorer.profilePhoto": "தொழில்முறை தலைப்படம்",
    "fileExplorer.bachelorCert": "பிஎஸ்சி தகவல் தொழில்நுட்பம் பட்ட சான்றிதழ்",
    "fileExplorer.googleCert": "Google டிஜிட்டல் மார்க்கெட்டிங் சான்றிதழ்",
  },
  ar: {
    // Common
    "common.language": "اللغة",
    "common.english": "English",
    "common.chinese": "中文",
    "common.malay": "Bahasa Melayu",
    "common.tamil": "தமிழ்",
    "common.arabic": "العربية",
    "common.learnMore": "أعرف أكثر",
    "common.contactMe": "اتصل بي",
    "common.downloadResume": "تحميل السيرة الذاتية",
    "common.resume": "السيرة الذاتية",
    "common.scrollTo": "التمرير إلى {section}",
    "common.loading": "جار التحميل...",
    "common.close": "إغلاق",
    "common.open": "فتح",
    "common.view": "عرض",
    "common.hide": "إخفاء",
    "common.show": "عرض",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تحرير",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.all": "الكل",
    "common.none": "لا شيء",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.success": "نجاح",
    "common.error": "خطأ",
    "common.warning": "تحذير",
    "common.info": "معلومات",

    // Navigation
    "nav.home": "الصفحة الرئيسية",
    "nav.about": "حول",
    "nav.experience": "الخبرة",
    "nav.skills": "المهارات",
    "nav.projects": "المشاريع",
    "nav.services": "الخدمات",
    "nav.testimonials": "الشهادات",
    "nav.education": "التعليم",
    "nav.contact": "اتصل",
    "nav.scrollTo": "التمرير إلى {section}",

    // Hero
    "hero.tagline": "تصميم الحلول الرقمية",
    "hero.title": "Kaung Sithu Linn",
    "hero.subtitle": "مطور برامج",
    "hero.jobTitle": "مطور برامج",
    "hero.description": "مطور ذو خبرة تزيد عن 4 سنوات في تصميم واجهات المستخدم البديهية، وإجراء اختبارات شاملة، وتقديم تطبيقات عالية الجودة تلبي المتطلبات المعقدة. متخصص في أنظمة نقاط البيع، واكتشاف الاحتيال، والقياسات الحيوية السلوكية.",
    "hero.githubProfile": "ملف GitHub",
    "hero.linkedinProfile": "ملف LinkedIn",
    "hero.emailContact": "الاتصال عبر البريد الإلكتروني",
    "hero.portfolioWebsite": "موقع المحفظة",
    "hero.downloadResume": "تحميل السيرة الذاتية",
    "hero.resume": "السيرة الذاتية",
    "hero.learnMore": "أعرف أكثر",
    "hero.contactMe": "اتصل بي",
    "hero.profileImageAlt": "Kaung Sithu Linn - مطور برامج",

    // About
    "about.title": "حول",
    "about.paragraph1": "بصفتي مطور برامج شغوف مقيم في سنغافورة، أتخصص في تطوير التطبيقات القوية مع التركيز على تجربة المستخدم وتحسين النظام. مع أكثر من 4 سنوات في eVolva Software House، قمت بتحويل العمليات التجارية من خلال أنظمة نقاط البيع المبتكرة وحلول الشبكات.",
    "about.paragraph2": "يركز بحثي الأخير على القياسات الحيوية السلوكية المتقدمة واكتشاف الاحتيال باستخدام التعلم الآلي. أنا أيضًا معتمد في أساسيات التسويق الرقمي، مما يسمح لي بربط التطوير التقني باستراتيجيات السوق الفعالة. أنا حاليًا أتابع درجة الماجستير في تكنولوجيا المعلومات مع تخصص في المعلوماتية التجارية في جامعة جيمس كوك في سنغافورة، حيث أواصل توسيع خبرتي في تحليلات البيانات وتطبيقات الذكاء الاصطناعي.",
    "about.quote": "أعتقد في إنشاء التكنولوجيا التي لا تحل المشكلات فحسب، بل تعزز التجارب البشرية. هدفي هو بناء حلول آمنة وفعالة وسهلة الاستخدام تحدث فرقًا حقيقيًا.",
    "about.decorativeImageAlt": "خلفية زخرفية",
    "about.skills.frontend.title": "الواجهة الأمامية",
    "about.skills.frontend.description": "JavaScript, HTML5, CSS, تصميم واجهة المستخدم",
    "about.skills.backend.title": "الواجهة الخلفية",
    "about.skills.backend.description": "Python, Java, C++, .NET",
    "about.skills.database.title": "قاعدة البيانات",
    "about.skills.database.description": "SQL, إدارة البيانات",
    "about.skills.ai.title": "الذكاء الاصطناعي/التعلم الآلي",
    "about.skills.ai.description": "القياسات الحيوية السلوكية, التعلم العميق",
    "about.skills.marketing.title": "التسويق الرقمي",
    "about.skills.marketing.description": "تحسين محركات البحث, التحليلات, استراتيجية المحتوى",
    "about.skills.languages.title": "اللغات",
    "about.skills.languages.description": "الإنجليزية, البورمية, الصينية, اليابانية",
    
    // Header
    "header.about": "حول",
    "header.experience": "الخبرة",
    "header.skills": "المهارات",
    "header.services": "الخدمات",
    "header.education": "التعليم",
    "header.contact": "اتصل",
    
    // Skills
    "skills.title": "المهارات والخبرات",
    "skills.frontend": "تطوير الواجهة الأمامية",
    "skills.frontend.tech": "JavaScript, HTML5, CSS",
    "skills.frontend.desc": "بناء واجهات مستخدم تفاعلية واستجابية باستخدام تقنيات الويب الحديثة.",
    "skills.backend": "تطوير الواجهة الخلفية",
    "skills.backend.tech": "Python, Java, C++, .NET",
    "skills.backend.desc": "إنشاء تطبيقات خادم قوية مع التركيز على الأداء والموثوقية.",
    "skills.database": "إدارة قاعدة البيانات",
    "skills.database.tech": "SQL, إدارة البيانات",
    "skills.database.desc": "تصميم وتنفيذ مخططات واستعلامات قاعدة البيانات بكفاءة لإدارة البيانات المثلى.",
    "skills.uiux": "تصميم واجهة المستخدم وتجربة المستخدم",
    "skills.uiux.tech": "تصميم واجهة المستخدم",
    "skills.uiux.desc": "تصميم واجهات مستخدم بديهية مع التركيز على سهولة الاستخدام وإمكانية الوصول.",
    "skills.ml": "التعلم الآلي",
    "skills.ml.tech": "القياسات الحيوية السلوكية, التعلم العميق",
    "skills.ml.desc": "تطوير نماذج التعلم الآلي لاكتشاف الاحتيال والتحقق من المستخدم باستخدام الأنماط السلوكية.",
    "skills.programming": "لغات البرمجة",
    "skills.programming.tech": "JavaScript, Python, Java, C++",
    "skills.programming.desc": "كتابة كود فعال بلغات برمجة متعددة لتطبيقات متنوعة.",
    "skills.multilingual": "متعدد اللغات",
    "skills.multilingual.tech": "الإنجليزية, البورمية, الصينية, اليابانية",
    "skills.multilingual.desc": "التواصل بفعالية عبر لغات متعددة للتعاون الدولي.",
    "skills.communication": "الاتصال",
    "skills.communication.tech": "الكتابة التقنية, التحدث العام",
    "skills.communication.desc": "نقل المفاهيم التقنية المعقدة بوضوح إلى كل من الجماهير التقنية وغير التقنية.",
    "skills.optimization": "تحسين النظام",
    "skills.optimization.tech": "ضبط الأداء, حلول الشبكة",
    "skills.optimization.desc": "تحسين أداء النظام وحل المشكلات التقنية المعقدة لتحقيق التشغيل الأمثل.",
    "skills.research": "البحث",
    "skills.research.tech": "البحث الأكاديمي, مراجعة الأدبيات",
    "skills.research.desc": "إجراء بحث شامل لتحديد الفجوات واقتراح حلول مبتكرة في التكنولوجيا.",

    // Experience
    "experience.title": "الخبرة المهنية",
    "experience.company": "eVolva Software House",
    "experience.location": "ماندالاي، ميانمار",
    "experience.period": "ديسمبر 2018 - الآن",
    "experience.role": "مطور برامج ومختبر عميل",
    "experience.responsibilities.1": "تصميم وتطوير نظام نقاط البيع باستخدام Microsoft .NET لتبسيط إدارة المخزون والمخزون، مما يحسن الكفاءة التشغيلية",
    "experience.responsibilities.2": "ترقية نظام نقاط البيع Microsoft Access (Office 2003) القديم إلى تطبيق SQL مستقل حديث، مما يعزز الأداء",
    "experience.responsibilities.3": "حل مشكلات التداخل في الشبكة المحلية مع شبكة VPN من خلال تنفيذ حل نفق مخصص، مما يضمن استقرار الاتصال",
    "experience.responsibilities.4": "تقديم نظام نقاط بيع محسن يزيد من كفاءة المتجر بأكثر من 50٪، مما يقلل من وقت المعاملة ويحسن تتبع المخزون",
    "experience.responsibilities.5": "إجراء اختبارات شاملة وتدريب العملاء لضمان اعتماد سلس للأنظمة الجديدة",
    "experience.decorativeImageAlt": "خلفية زخرفية",
    "experience.keyAchievements": "الإنجازات الرئيسية",
    
    // Projects
    "projects.title": "المشاريع المميزة",
    "projects.viewProject": "عرض المشروع",
    "projects.hideCase": "إخفاء دراسة الحالة",
    "projects.viewCase": "عرض دراسة الحالة",
    "projects.challenge": "التحدي",
    "projects.approach": "النهج",
    "projects.results": "النتائج",
    "projects.technologies": "التقنيات المستخدمة",
    "projects.project1.title": "ديناميكيات الفأرة لاكتشاف الاحتيال في التقييم عبر الإنترنت",
    "projects.project1.period": "مايو 2024 - نوفمبر 2024",
    "projects.project1.description": "تطوير نموذج تعلم آلي لاكتشاف السلوك الاحتيالي أثناء التقييمات عبر الإنترنت باستخدام ديناميكيات الفأرة كقياس حيوي سلوكي.",
    "projects.project1.achievement1": "تحليل حركة الفأرة وأنماط النقر لإنشاء ملفات تعريف المستخدمين وتحديد الشذوذات التي تشير إلى الاحتيال",
    "projects.project1.achievement2": "تنفيذ تقنيات اختيار الميزات وتقييم نماذج تعلم آلي متعددة، وتحقيق دقة عالية في اكتشاف الاحتيال",
    "projects.project1.achievement3": "تحديد ميزات ديناميكيات الفأرة الرئيسية التي تميز بشكل أكبر للتحقق من المستخدم",
    "projects.project1.challenge": "واجهت المؤسسات التعليمية زيادة في حوادث الغش في التقييمات عبر الإنترنت، حيث أثبتت طرق المراقبة التقليدية عدم كفايتها لاكتشاف تقنيات الاحتيال المتقدمة.",
    "projects.project1.approach": "تطوير نظام قياس حيوي سلوكي غير تدخلي يحلل أنماط حركة الفأرة لتحديد السلوك الشاذ دون المساس بخصوصية المستخدم أو الحاجة إلى أجهزة إضافية.",
    "projects.project1.results": "حقق النظام دقة بنسبة 92٪ في اكتشاف السلوك الاحتيالي بمعدل إيجابي زائف يبلغ 3٪ فقط، مما يحسن بشكل كبير من نزاهة التقييم مع الحفاظ على تجربة مستخدم إيجابية.",
    "projects.project2.title": "نظام اكتشاف الاحتيال البيومتري لديناميكيات الفأرة باستخدام التعلم العميق",
    "projects.project2.period": "مايو 2024 - نوفمبر 2024",
    "projects.project2.description": "تطوير نظام اكتشاف الاحتيال باستخدام ديناميكيات الفأرة والتعلم العميق لتعزيز أمان التقييمات عبر الإنترنت.",
    "projects.project2.achievement1": "تنفيذ خطوط معالجة البيانات المسبقة لتحقيق قابلية استخدام البيانات بنسبة 100٪",
    "projects.project2.achievement2": "تصميم 12 مجموعة ميزات محسنة باستخدام طرق اختيار متقدمة",
    "projects.project2.achievement3": "تطوير واختبار نماذج تعلم عميق متعددة (ANN, LSTM, LSTM-CNN, LSTM-Transformer)",
    "projects.project2.achievement4": "بناء أدوات تصور البيانات لمراقبة أداء النظام",
    "projects.project2.achievement5": "تجاوز أهداف المشروع، وتحقيق دقة اكتشاف بنسبة 95٪ ومعدل سلبي كاذب أقل من 5٪",
    "projects.project2.challenge": "واجهت أنظمة اكتشاف الاحتيال الحالية صعوبة في التحليل في الوقت الفعلي وكانت تتطلب متطلبات حسابية عالية، مما يجعلها غير عملية للتنفيذ على نطاق واسع.",
    "projects.project2.approach": "الاستفادة من بنى التعلم العميق لإنشاء نظام خفيف الوزن وفعال قادر على التحليل في الوقت الفعلي مع الحد الأدنى من العبء الحسابي، مع التركيز على تحسين كل من الدقة والأداء.",
    "projects.project2.results": "قام النظام بمعالجة سلوك المستخدم في الوقت الفعلي بزمن انتقال أقل من 200 مللي ثانية، مع الحفاظ على دقة اكتشاف بنسبة 95٪ وتقليل المتطلبات الحسابية بنسبة 60٪ مقارنة بالحلول السابقة.",
    "projects.project3.title": "المصادقة المستمرة باستخدام القياسات الحيوية السلوكية",
    "projects.project3.period": "مايو 2024 - نوفمبر 2024",
    "projects.project3.description": "إجراء مراجعة أدبية حول استخدام القياسات الحيوية السلوكية، وخاصة ديناميكيات الفأرة وتحليل ضربات المفاتيح، للمصادقة المستمرة للمستخدم.",
    "projects.project3.achievement1": "البحث في الأساليب الحالية والتحديات والتحسينات المحتملة في هذا المجال",
    "projects.project3.achievement2": "تحديد الفجوات البحثية الرئيسية واقتراح طريقة مصادقة جديدة باستخدام أمان المعلومات البيومترية السلوكية في الوقت الفعلي (RBBIS)",
    "projects.project3.achievement3": "تطوير إطار عمل بحثي وخطة عمل لتنفيذ وتقييم الطريقة المقترحة",
    "projects.project3.challenge": "تعتمد طرق المصادقة التقليدية على التحقق لمرة واحدة، مما يخلق ثغرات أمنية بمجرد تسجيل دخول المستخدم، بينما غالبًا ما تخلق الطرق المستمرة احتكاكًا في تجربة المستخدم.",
    "projects.project3.approach": "تطوير إطار عمل للمصادقة المستمرة السلبية التي تراقب الأنماط السلوكية في الخلفية دون مقاطعة سير عمل المستخدم، والتكيف مع السلوك المتغير للمستخدم بمرور الوقت.",
    "projects.project3.results": "أظهر الإطار المقترح القدرة على تقليل حوادث الوصول غير المصرح به بنسبة تصل إلى 87٪ في البيئات المحاكاة، مع الحفاظ على تجربة مستخدم سلسة دون مطالبات مصادقة إضافية.",
    
    // Services
    "services.title": "خدماتي",
    "services.web": "تطوير تطبيقات الويب",
    "services.web.desc": "تطبيقات ويب مخصصة مبنية باستخدام React و Next.js، مع التركيز على الأداء وتجربة المستخدم.",
    "services.backend": "تطوير الواجهة الخلفية",
    "services.backend.desc": "حلول خادم قوية وقابلة للتوسع باستخدام Node.js و Express و Fastify.",
    "services.api": "تطوير API",
    "services.api.desc": "تصميم وتنفيذ API RESTful و GraphQL لتدفق البيانات السلس بين العميل والخادم.",
    "services.responsive": "تصميم استجابي",
    "services.responsive.desc": "تصميمات ويب استجابية تركز على الأجهزة المحمولة تعمل بسلاسة عبر جميع الأجهزة وأحجام الشاشات.",
    
    // Education
    "education.title": "التعليم والشهادات",
    "education.master": "ماجستير في تكنولوجيا المعلومات (المعلوماتية التجارية)",
    "education.master.institution": "جامعة جيمس كوك سنغافورة",
    "education.master.period": "مارس 2024 – أبريل 2025",
    "education.master.achievement1": "التخصص في تحليلات البيانات وذكاء الأعمال",
    "education.master.achievement2": "إجراء البحوث في القياسات الحيوية السلوكية واكتشاف الاحتيال",
    "education.master.achievement3": "تطوير نماذج تعلم آلي متقدمة لتطبيقات الأمان",
    "education.bachelor": "بكالوريوس في تكنولوجيا المعلومات",
    "education.bachelor.institution": "جامعة جيمس كوك سنغافورة",
    "education.bachelor.period": "نوفمبر 2022 – فبراير 2024",
    "education.bachelor.achievement1": "التركيز على تطوير البرمجيات وتصميم الأنظمة",
    "education.bachelor.achievement2": "إكمال المشاريع في تصميم واجهة المستخدم وتطوير التطبيقات",
    "education.bachelor.achievement3": "اكتساب الخبرة في لغات البرمجة والأطر المتعددة",
    "education.bachelor.achievement4": "منحت في 7 مارس 2024 بمعدل تراكمي 5.27",
    "education.diploma": "الدبلوم الوطني العالي في هندسة البرمجيات (المستوى 5)",
    "education.diploma.institution": "INET IT ACADEMY",
    "education.diploma.period": "مارس 2018 – أكتوبر 2022",
    "education.diploma.achievement1": "تطوير المعرفة الأساسية في مبادئ هندسة البرمجيات",
    "education.diploma.achievement2": "إكمال المشاريع العملية في تطوير التطبيقات",
    "education.diploma.achievement3": "تعلم منهجيات تحليل وتصميم الأنظمة",
    "education.achievements": "الإنجازات الرئيسية",
    "education.certifications": "الشهادات والاختبارات",
    "education.verification": "تفاصيل التحقق",
    "education.cert1.title": "بكالوريوس في تكنولوجيا المعلومات",
    "education.cert1.issuer": "جامعة جيمس كوك سنغافورة",
    "education.cert1.date": "7 مارس 2024",
    "education.cert1.description": "شهادة رسمية لدرجة بكالوريوس في تكنولوجيا المعلومات، منحت في 7 مارس 2024. توفر الدرجة أساسًا شاملاً في مفاهيم تكنولوجيا المعلومات والبرمجة وتصميم قواعد البيانات وتطوير الأنظمة.",
    "education.cert1.verificationMessage": "تفاصيل التحقق غير متاحة لهذه الشهادة.",
    "education.cert2.title": "أساسيات التسويق الرقمي",
    "education.cert2.issuer": "Google Digital Garage",
    "education.cert2.date": "3 أبريل 2023",
    "education.cert2.description": "شهادة شاملة تغطي أساسيات التسويق الرقمي، بما في ذلك تحسين محركات البحث والتسويق عبر وسائل التواصل الاجتماعي والتحليلات.",
    "education.cert3.title": "تحليلات البيانات من Google",
    "education.cert3.issuer": "Google",
    "education.cert3.date": "2023",
    "education.cert3.description": "شهادة مهنية تغطي تحليل البيانات والتصور والتفسير باستخدام أدوات تحليلات Google.",
    "education.verifyAuthenticity": "تحقق من صحة هذه الشهادة في:",
    "education.certificateId": "معرف الشهادة:",
    "education.verificationInfo": "معلومات التحقق",
    "education.verifyButton": "تحقق من الشهادة",
    
    // Contact
    "contact.title": "اتصل بي",
    "contact.info": "معلومات الاتصال",
    "contact.email": "البريد الإلكتروني",
    "contact.phone": "الهاتف",
    "contact.address": "العنوان",
    "contact.connect": "تواصل معي",
    "contact.connect.desc": "أنا دائمًا منفتح على مناقشة المشاريع الجديدة والأفكار الإبداعية أو الفرص لتكون جزءًا من رؤيتك.",
    "contact.form.name": "الاسم",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.subject": "الموضوع",
    "contact.form.message": "الرسالة",
    "contact.form.send": "إرسال الرسالة",
    "contact.form.sending": "جار الإرسال...",
    "contact.form.success": "شكرًا لك! تم إرسال رسالتك بنجاح. سأعود إليك قريبًا.",
    "contact.form.error": "فشل في إرسال النموذج. حاول مرة اخرى.",
    "contact.form.nameRequired": "يجب أن يكون الاسم مكونًا من حرفين على الأقل",
    "contact.form.emailRequired": "يرجى إدخال عنوان بريد إلكتروني صالح",
    "contact.form.subjectRequired": "يجب أن يكون الموضوع مكونًا من 5 أحرف على الأقل",
    "contact.form.messageRequired": "يجب أن تكون الرسالة مكونة من 10 أحرف على الأقل",
    
    // Testimonials
    "testimonials.title": "شهادات العملاء",
    "testimonials.prev": "الشهادة السابقة",
    "testimonials.next": "الشهادة التالية",
    "testimonials.goto": "انتقل إلى الشهادة {number}",
    "testimonials.client1.quote": "خبرة Kaung في تطوير نظام نقاط البيع لدينا حولت عمليات أعمالنا. انتباهه للتفاصيل ومهاراته في حل المشكلات استثنائية.",
    "testimonials.client1.name": "سارة تشين",
    "testimonials.client1.title": "مدير العمليات، حلول RetailTech",
    "testimonials.client2.quote": "العمل مع Kaung على نظام اكتشاف الاحتيال لدينا كان تغييرًا في اللعبة. فهمه العميق للقياسات الحيوية السلوكية والتعلم الآلي قدم نتائج تتجاوز توقعاتنا.",
    "testimonials.client2.name": "مايكل رودريغيز",
    "testimonials.client2.title": "CTO، SecureFinance",
    "testimonials.client3.quote": "قدرة Kaung على ترجمة المتطلبات التقنية المعقدة إلى حلول سهلة الاستخدام رائعة. عمله على البنية التحتية لشبكتنا حسن بشكل كبير من استقرار نظامنا.",
    "testimonials.client3.name": "بريا شارما",
    "testimonials.client3.title": "مدير تكنولوجيا المعلومات، Global Connect",

    // System Monitor
    "systemMonitor.title": "مراقب النظام",
    "systemMonitor.systemTime": "وقت النظام",
    "systemMonitor.cpuUsage": "استخدام وحدة المعالجة المركزية",
    "systemMonitor.memoryUsage": "استخدام الذاكرة",
    "systemMonitor.networkActivity": "نشاط الشبكة",
    "systemMonitor.skillsMonitor": "مراقب المهارات",
    "systemMonitor.show": "عرض الواجهة",
    "systemMonitor.hide": "إخفاء الواجهة",

    // Terminal
    "terminal.title": "KSL DevConsole",
    "terminal.welcome": "مرحبًا بك في محفظة Kaung Sithu Linn. اكتب 'help' لرؤية الأوامر المتاحة.",
    "terminal.help": "الأوامر المتاحة",
    "terminal.about": "حول",
    "terminal.skills": "المهارات",
    "terminal.projects": "المشاريع",
    "terminal.contact": "اتصل",
    "terminal.experience": "الخبرة",
    "terminal.education": "التعليم",
    "terminal.clear": "مسح المحطة",
    "terminal.exit": "الخروج من وضع المحطة",
    "terminal.askAI": "اسأل المساعد الذكي",

    // File Explorer
    "fileExplorer.title": "مستكشف المحفظة",
    "fileExplorer.projects": "المشاريع",
    "fileExplorer.resume": "السيرة الذاتية",
    "fileExplorer.certificates": "الشهادات",
    "fileExplorer.mainPython": "البرنامج النصي الرئيسي لنظام اكتشاف الاحتيال",
    "fileExplorer.model": "نموذج التعلم الآلي المدرب",
    "fileExplorer.readme": "وثائق المشروع",
    "fileExplorer.authSystem": "تنفيذ نظام المصادقة",
    "fileExplorer.researchPaper": "ورقة بحثية حول القياسات الحيوية السلوكية",
    "fileExplorer.currentResume": "السيرة الذاتية المهنية الحالية",
    "fileExplorer.profilePhoto": "صورة الملف الشخصي المهنية",
    "fileExplorer.bachelorCert": "شهادة بكالوريوس في تكنولوجيا المعلومات",
    "fileExplorer.googleCert": "شهادة التسويق الرقمي من Google",
  },
}
